Challenge

Problem Statement

In [350]:
#import required packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Description

Now we write a code that displays all the columns whenever we look at the data information.

In [351]:
pd.set_option('display.max_columns', None)

Now, we are going to read the datasets and see the columns that they contain to check the variable of interest, and therefore decide which datasets we're going to work with.

In [352]:
#code that reads in the data from 2012 and gives it the variable name, data_2012
data_2012 = pd.read_csv('/content/sample_data/ghs-2012-person-v2.1.csv', encoding = 'latin-1')
data_2012.head() #displays the first five rows of the data

,UqNr,PersonNR,PSU,Prov,B_Nights,Gender,Age,Age_grp,Race,Q11relsh,Q12amarst,Q12bspou,Q12cpsnn,Q13afath,Q13bfpar,Q13cfpsn,Q14amoth,Q14bmpar,Q14cmpsn,Q15fcare,Q16hiedu,Q17atecd,Q18aecd,Q18becd1,Q18becd2,Q18becd3,Q19wrtn,Q19read,Q19form,Q19wrtl,Q19cal,Q19rdsn,Q110atte,Q111rsnn,Q112edui,Q113ppriv,Q114dlrn,Q115amod,Q115btim,Q115cnr,Q115dNNI,Q116feet,Q117rnfe,Q118burs,Q119book,Q119poor,Q119lack,Q119badc,Q119fees,Q119clas,Q119tabs,Q119pman,Q119othr,Q120grde,Q121same,Q122afood,Q122BEFOOD,Q123aviol,Q123bviol1,Q123bviol2,Q123bviol3,Q123bviol4,Q123bviol5,Q123bviol6,Q124aabs,Q124bDAY,Q124crsn,Q125medi,Q126ainju,Q126bflu,Q126bdia,Q126btbc,Q126bsub,Q126bdep,Q126bDBT,Q126bblo,Q126bsex,Q126bcan,Q126bmvh,Q126bgun,Q126bstr,Q126bmtr,Q126both,Q126bdnk,Q127acon,Q127bynt,Q128aasm,Q128adiab,Q128acan,Q128ahiv,Q128ahbp,Q128arth,Q128aoth,Q128basm,Q128bdiab,Q128bcan,Q128bhiv,Q128bhbp,Q128brth,Q128both,Q129apre,Q129bsta,Q130see,Q130hea,Q130wal,Q130rem,Q130sel,Q130com,Q131eye,Q131haid,Q131wst,Q131wch,Q131cmed,Q131oth,Q132asg,Q132boag,Q132bdis,Q132bcsg,Q132bcar,Q132bfos,Q132bwvt,Q132bgrn,Q132bsoc,Q133DISG,Q134csgw,Q135CCG,Q135DMVL,Q135DRUG,Q135CPS,Q135CS,Q136Resp,Q21awge,Q21bbus,Q21cvol,Q21dret,Q22asto,Q22bsp,Q23salc,Q24atm,Q24bmin,Q25sec,Q26aLOOK,Q26bSTART,Q26cRNSW,Q26dAccJob,Q27aMotBus,Q27bMOTVT,undisab,disab,Sevdisab,literacy3b,Q22Msal,Stratum,GeoType,Metro,person_wgt
0,101000170000001501,1,10100017000,Western Cape,Yes,Male,31,30 - 34 years,White,Head/acting head,Legally married,Yes,2,Yes,No,Not applicable,Yes,No,Not applicable,Not applicable,N4/NTC 4,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,No,No,No,No,Yes,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Not applicable,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,1,Yes,No,No,Not applicable,7000,Per month,Unspecified,Own car/other private vehicle/company vehicle,Less than 15 minutes,In the formal sector (registered to perform ac...,Unspecified,Unspecified,Unspecified,Unspecified,No,Not applicable,Not disabled,Not disabled,Not disabled,Literate,7000,101501,Rural formal,Non metrol,523.444231
1,101000170000001501,2,10100017000,Western Cape,Yes,Female,27,25 - 29 years,White,Husband/wife/partner of person 01,Legally married,Yes,1,Yes,No,Not applicable,Yes,No,Not applicable,Not applicable,Diploma with Grade 12/Std 10,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,1,No,Yes,No,Not applicable,3000,Per month,Unspecified,Own car/other private vehicle/company vehicle,1530 minutes,In the formal sector (registered to perform ac...,Unspecified,Unspecified,Unspecified,Unspecified,No,Not applicable,Not disabled,Not disabled,Not disabled,Literate,3000,101501,Rural formal,Non metrol,523.444231
2,101000170000005701,1,10100017000,Western Cape,Yes,Male,43,40 - 44 years,Coloured,Head/acting head,Living together like husband and wife,Yes,2,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Not applicable,Grade 10/ Standard 8/ Form 3,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,2,Yes,No,No,Not applicable,180,Per week,Unspecified,Unspecified,Less than 15 minutes,In the formal sector (registered to perform ac...,No,Unspecified,Unspecified,Unspecified,No,Not applicable,Not disabled,Not disabled,Not disabled,Literate,720,101501,Rural formal,Non metrol,261.888754
3,101000170000005701,2,10100017000,Western Cape,Yes,Female,46,45 - 49 years,Coloured,Husband/wife/partner of person 01,Living together like husband and wife,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Not applicable,Grade 7/Standard 5/ABET 3,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No money for fees,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,2,No,No,No,No,88888888,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,Not applicable,Not applicable,No,Not applicable,Not disabled,Not disabled,Not disabled,Literate,Not applicable,101501,Rural formal,Non metrol,261.888754
4,101000170000009901,1,10100017000,Western Cape,Yes,Male,52,50 - 54 years,Coloured,Head/acting head,Legally married,Yes,2,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Not applicable,Grade 1/ Sub A/Class 1,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,A lot of difficulty,A lot of difficulty,A lot of difficulty,A lot of difficulty,A lot of difficulty,A lot of difficulty,No,He or she is working at home or business/job,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,2,Yes,No,No,Not applicable,350,Per week,Unspecified,Walking,Less than 15 minutes,In the formal sector (registered to perform ac...,Unspecified,Unspecified,Unspecified,Unspecified,No,Not applicable,Not disabled,Not disabled,Not disabled,Illiterate,1400,101501,Rural formal,Non metrol,265.495279

In [353]:
#code that reads in the data from 2013 and gives it the variable name, data_2013
data_2013 = pd.read_csv('/content/sample_data/ghs-2013-person-v1.csv', encoding = 'latin-1')
data_2013.head() #displays the first five rows of the dataset

,UqNr,PersonNR,PSU,Prov,B_Nights,Gender,Age,Age_grp,Race,Q11RELSH,Q12aMARST,Q12BSPOU,Q12CPSNN,Q13aFATH,Q13bFPAR,Q13CFPSN,Q14aMOTH,Q14bMPAR,Q14CMPSN,Q15FCARE,Q16HIEDU,Q17ATECHILD,Q17BDA,Q18ECD,Q19WRTN,Q19READ,Q19FORM,Q19WRTL,Q19CAL,Q19RDSN,Q110ATTE,Q111RSNN,Q112EDUI,Q113PPRIV,Q114DLRN,Q115aMOD,Q115bTIM,Q115cNR,Q115dNNI,Q116FEET,Q117RNFE,Q118BURS,Q119AWORKBOOKS,Q119BTEXTBOOKS,Q119cBOOK,Q119cPOOR,Q119cLACK,Q119cBADC,Q119cFEES,Q119cCLAS,Q119cTABS,Q119cPMAN,Q119cOTHR,Q120GRDE,Q121SAME,Q122aFOOD,Q122bEFOOD,Q123aVIOL,Q123bVIOL1,Q123bVIOL2,Q123bVIOL3,Q123bVIOL4,Q123bVIOL5,Q123bVIOL6,Q124aABS,Q124bDAY,Q124cRSN,Q21MEDI,Q22GENHEALTH,Q23aIllness,Q23bFLU,Q23bDIA,Q23bTBC,Q23bSUB,Q23bDEP,Q23bDBT,Q23bBLO,Q23bSEX,Q23BCAN,Q23bPNEU,Q23bBRON,Q23bEPIL,Q23bMEN,Q23bCHOLE,Q23bOSTER,Q23bOTH,Q23bDNK,Q24aCON,Q24bYNT,Q25aInjuries,Q25BINJ,Q26aASM,Q26aDBT,Q26aCAN,Q26aHIV,Q26aHBP,Q26aRTH,Q26aSTRK,Q26aHEART,Q26aTB,Q26aOTH,Q26bASM,Q26bDBT,Q26bCAN,Q26bHIV,Q26bHBP,Q26bRTH,Q26bSTRK,Q26bHEART,Q26bTB,Q26bOTH,Q27aPRE,Q27bSTA,Q28SEE,Q28HEA,Q28WAL,Q28REM,Q28SEL,Q28COM,Q29EYE,Q29HAID,Q29WST,Q29WCH,Q29CMED,Q29OTH,Q31asg,Q31bOAG,Q31bDIS,Q31bCSG,Q31bCAR,Q31bFOS,Q31bWVT,Q31bGRN,Q31bSOC,Q32DISG,Q33CSGW,Q34CCG,Q34DMVL,Q34DRUG,Q34CPS,Q34CS,Q41aWGE,Q41bBUS,Q41cVOL,Q41dRET,Q42aSTO,Q42bSP,Q43SALC,Q44aTM,Q44bMIN,Q45SEC,Q46aLOOK,Q46bSTART,Q46cRNSW,Q46dAccJob,Q47JCR,Q48CELL,Q49RELIGIOUS,Q410ATEREL,Q411RESP,undisab,disab,Sevdisab,Literacy3b,Stratum,geotype,Metro,Rotation,person_wgt
0,101000170000001501,1,10100017000,Western Cape,Yes,Male,32,7,White,Head/acting head,Legally married,Yes,2,Yes,No,88,Yes,No,88,Not applicable,NTC 3/ N3/NC (V)/Level 4,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,8,Not applicable,Yes,Good,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Experienced difficulty getting a diagnosis before,No,Not applicable,Yes,No,No,No,No,No,No,No,No,No,Yes,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Not applicable,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,Yes,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,Yes,No,No,Unspecified,10000,Per month,99,Walking,Less than 15 minutes,In the formal sector (registered to perform ac...,Unspecified,Unspecified,99,Unspecified,No,Yes,Christian,Usually once or twice a month,2,Not disabled,Not disabled,Not disabled,Literate,101501,Rural formal,Non metro,Quarter 4,461.691059
1,101000170000001501,2,10100017000,Western Cape,Yes,Female,28,6,White,Husband/wife/partner of person 01,Legally married,Yes,1,Yes,No,88,Yes,No,88,Not applicable,Diploma with Grade 12/Std 10,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Family commitment (e.g. child minding),Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,8,Not applicable,Yes,Good,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Experienced difficulty getting a diagnosis before,No,Not applicable,No,No,No,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,The child has been born alive,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,No,No,No,888888888,Not applicable,88,Not applicable,Not applicable,Not applicable,No,No,88,Not applicable,No,Yes,Christian,Usually once or twice a month,2,Not disabled,Not disabled,Not disabled,Literate,101501,Rural formal,Non metro,Quarter 4,461.691059
2,101000170000001501,3,10100017000,Western Cape,Yes,Male,0,1,White,Son/daughter/stepchild/adopted child of person 01,Single and have never been married/never lived...,Not applicable,88,Yes,Yes,1,Yes,Yes,2,Unspecified,No schooling,NaN,"At home with parent, foster parent or guardian",No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,8,Not applicable,Yes,Good,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Experienced difficulty getting a diagnosis before,No,Not applicable,No,No,No,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No difficulty,No difficulty,Unable to do,No difficulty,Unable to do,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,888888888,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,No,Christian,Usually once or twice a month,2,Disabled,Disabled,Disabled,Literate,101501,Rural formal,Non metro,Quarter 4,461.691059
3,101000170000005701,1,10100017000,Western Cape,Yes,Male,45,10,Coloured,Head/acting head,Living together like husband and wife,Yes,2,No,Not applicable,88,No,Not applicable,88,Not applicable,Grade 9/Standard 7/Form 2/AET 4,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,8,Not applicable,No,Fair,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Experienced difficulty getting a diagnosis before,No,Not applicable,No,No,No,No,No,No,No,No,Yes,No,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Yes,Unspecified,Not applicable,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,Yes,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,Yes,No,No,Unspecified,450,Per week,99,Walking,Less than 15 minutes,In the formal sector (registered to perform ac...,Unspecified,Unspecified,99,Unspecified,No,No,Christian,Never,1,Not disabled,Not disabled,Not disabled,Literate,101501,Rural formal,Non metro,Quarter 4,372.137808
4,101000170000005701,2,10100017000,Western Cape,Yes,Female,48,10,Coloured,Husband/wife/partner of person 01,Living together like husband and wife,Yes,1,No,Not applicable,88,No,Not applicable,88,Not applicable,Grade 6/Standard 4,Not applicable,Not applicable,Not applicable,Some difficulty,Some difficulty,Some difficulty,Some difficulty,Some difficulty,Some difficulty,No,He or she is working at home or business/job,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,88,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,8,Not applicable,No,Good,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Experienced difficulty getting a diagnosis before,No,Not applicable,No,No,No,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,Yes,No,No,Unspecified,350,Per week,99,Walking,Less than 15 minutes,In the formal sector (registered to perform ac...,Unspecified,Unspecified,99,Unspecified,No,No,Christian,Never,2,Not disabled,Not disabled,Not disabled,Literate,101501,Rural formal,Non metro,Quarter 4,372.137808

In [354]:
#code that reads in the data from 2014 and gives it the variable name, data_2014
data_2014 = pd.read_csv('/content/sample_data/ghs-2014-person-v1.csv', encoding = 'latin-1')
data_2014.head() #displays the first five rows of the dataset

,uqnr,personnr,psu,prov,B_NIGHTS,gender,Age,age_grp,race,q11RELSH,q12aMARST,Q12bSPOU,Q12CPSNN,Q13aFATH,Q13bFalive,Q13cFPAR,Q13dFPSN,Q14aMOTH,Q14bMalive,Q14cMPAR,Q14dMPSN,Q15HIEDU,Q16ATECHILD,Q17DA,Q18ECD,Q19WRTN,Q19READ,Q19FORM,Q19WRTL,Q19CAL,Q19RDSN,Q110ATTE,Q111RSNN,Q112EDUI,Q113PPRIV,Q114DLRN,Q115aMOD,Q115bTIM,Q115cNR,Q115dNNI,Q116FEET,Q117RNFE,Q118BURS,Q119ALanguage,Q119Amathematics,Q119BTEXTBOOKS,Q119cBOOK,Q119cPOOR,Q119cLACK,Q119cBADC,Q119cFEES,Q119cCLAS,Q119cTABS,Q119cPMAN,Q119cOTHR,Q120GRDE,Q121SAME,Q122aFOOD,Q122bEFOOD,Q123aVIOL,Q123bVIOL1,Q123bVIOL2,Q123bVIOL3,Q123bVIOL4,Q123bVIOL5,Q123bVIOL6,Q124aABS,Q124bDAY,Q124cRSN,Q21MEDI,Q22GENHEALTH,Q23FLU,Q23DIA,Q23SCblood,Q23SUB,Q23DEP,Q23SEX,Q23PNEU,Q23BRON,Q23EPIL,Q24aCON,Q24bYNT,Q25aMVHoccupant,Q25aMVHpedestrian,Q25aBCL,Q25aGUN,Q25aSTR,Q25aCrime,Q25aFIRE,Q25aACCP,Q25aINTP,Q25aSPORTS,Q25aOTH,Q25bmiss,Q26aASM,Q26aDBT,Q26aCAN,Q26aHIV,Q26aHBP,Q26aRTH,Q26aSTRK,Q26aHEART,Q26aTB,Q26aMental,Q26aEPIL,Q26aMEN,Q26aPNEU,Q26aBRON,Q26aCHOLE,Q26aOSTER,Q26aOTH,Q26bASM,Q26bDBT,Q26bCAN,Q26bHIV,Q26bHBP,Q26bRTH,Q26bSTRK,Q26bHEART,Q26bTB,Q26bMental,Q26bEPIL,Q26bMEN,Q26bPNEU,Q26bBRON,Q26bCHOLE,Q26bOSTER,Q26bOTH,Q27aPRE,Q27bSTA,Q28SEE,Q28HEA,Q28WAL,Q28REM,Q28SEL,Q28COM,Q29EYE,Q29HAID,Q29WST,Q29WCH,Q29CMED,Q29OTH,Q31aSG,Q31bOAG,Q31bDIS,Q31bCSG,Q31bCAR,Q31bFOS,Q31bWVT,Q31bGRN,Q31bSOC,Q32DISG,Q41aWGE,Q41bBUS,Q41cVOL,Q41dRET,Q42aSTO,Q42bSP,Q43SALC,Q44aTM,Q44bMIN,Q45SEC,Q46aLOOK,Q46bSTART,Q46cRNSW,Q46dAccJOB,Q47JCR,Q48CELL,Q49RELIGIOUS,Q410ATEREL,Q411RESP,undisab,disab,sevdisab,literacy3b,geotype,q42msal,Metro,employ_Status1,employ_Status2,stratum,rotation,person_wgt
0,101000170000001501,1,10100017000,1,1,1,33,7,4,1,2,1,2,1,8,2,88,1,8,9,99,12,8,8,8,8,8,8,8,8,8,2,6,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,1,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,8,1,1,1,1,1,1,2,2,2,2,1,2,2,8,8,8,8,8,8,8,8,8,1,2,2,9,8000,2,99,2,1,1,9,9,99,9,2,1,1,4,2,0,0,0,0,5,8000,2,1,1,101501,4,512.302826
1,101000170000001501,2,10100017000,1,1,2,29,6,4,2,1,1,1,1,8,2,88,1,8,9,99,23,8,8,8,8,8,8,8,8,8,2,8,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,1,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,2,9,5000,2,99,1,8,2,9,9,99,9,2,1,1,4,2,0,0,0,0,5,5000,2,1,1,101501,4,512.302826
2,101000170000001501,3,10100017000,1,1,1,1,1,4,3,7,8,88,1,8,1,1,1,8,1,2,98,6,1,1,8,8,8,8,8,8,8,88,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,1,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,8,8,8,8,8,8,8,8,8,8,8,8,888888888,8,88,88,8,8,8,8,88,8,8,2,99,4,2,0,0,0,0,5,888888888,2,8,8,101501,4,512.302826
3,101000170000005701,1,10100017000,1,1,1,46,10,2,1,2,1,2,2,2,8,88,2,2,8,88,10,8,8,8,8,8,8,8,8,8,2,6,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,5,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,1,2,2,9,450,1,99,2,1,1,9,9,99,9,2,2,1,2,2,0,0,0,0,5,1800,2,1,1,101501,4,304.050736
4,101000170000005701,2,10100017000,1,1,2,49,10,2,2,2,1,1,2,2,8,88,2,2,8,88,1,8,8,8,1,1,2,2,1,1,2,10,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,2,2,2,888888888,8,88,88,8,8,2,2,88,8,2,2,1,2,2,0,0,0,0,5,888888888,2,9,3,101501,4,304.050736

In [355]:
#code that reads in the data from 2015 and gives it the variable name, data_2015
data_2015 = pd.read_csv('/content/sample_data/ghs-2015-person-v1.csv', encoding = 'latin-1')
data_2015.head() #displays the first five rows of the dataset

,uqnr,personnr,psu,prov,B_NIGHTS,gender,Age,age_grp1,race,q11RELSH,q12aMARST,Q12bSPOU,Q12CPSNN,Q13aFATH,Q13bFalive,Q13cFPAR,Q13dFPSN,Q14aMOTH,Q14bMalive,Q14cMPAR,Q14dMPSN,Q15HIEDU,Q16ATECHILD,Q17DA,Q18ECD,Q19WRTN,Q19READ,Q19FORM,Q19WRTL,Q19CAL,Q19RDSN,Q110ATTE,Q111RSNN,Q112EDUI,Q113PPRIV,Q114DLRN,Q115aMOD,Q115bTIM,Q115cNR,Q115dNNI,Q116FEET,Q117RNFE,Q118BURS,Q119ALanguage,Q119Amathematics,Q119BTEXTBOOKS,Q119cBOOK,Q119cPOOR,Q119cLACK,Q119cBADC,Q119cFEES,Q119cCLAS,Q119cTABS,Q119cPMAN,Q119cOTHR,Q120GRDE,Q121SAME,Q122aFOOD,Q122bEFOOD,Q123aVIOL,Q123bVIOL1,Q123bVIOL2,Q123bVIOL3,Q123bVIOL4,Q123bVIOL5,Q123bVIOL6,Q124aABS,Q124bDAY,Q124cRSN,Q21MEDI,Q22GENHEALTH,Q23FLU,Q23DIA,Q23SCblood,Q23SUB,Q23DEP,Q23SEX,Q23PNEU,Q23BRON,Q23EPIL,Q24aCON,Q24bYNT,Q25aMVHoccupant,Q25aMVHpedestrian,Q25aBCL,Q25aGUN,Q25aSTR,Q25aCrime,Q25aFIRE,Q25aACCP,Q25aINTP,Q25aSPORTS,Q25aOTH,Q25bmiss,Q26aASM,Q26aDBT,Q26aCAN,Q26aHIV,Q26aHBP,Q26aRTH,Q26aSTRK,Q26aHEART,Q26aTB,Q26aMental,Q26aEPIL,Q26aMEN,Q26aPNEU,Q26aBRON,Q26aCHOLE,Q26aOSTER,Q26aOTH,Q26bASM,Q26bDBT,Q26bCAN,Q26bHIV,Q26bHBP,Q26bRTH,Q26bSTRK,Q26bHEART,Q26bTB,Q26bMental,Q26bEPIL,Q26bMEN,Q26bPNEU,Q26bBRON,Q26bCHOLE,Q26bOSTER,Q26bOTH,Q27aPRE,Q27bSTA,Q28SEE,Q28HEA,Q28WAL,Q28REM,Q28SEL,Q28COM,Q29EYE,Q29HAID,Q29WST,Q29WCH,Q29CMED,Q29OTH,Q31aSG,Q31bOAG,Q31bDIS,Q31bCSG,Q31bCAR,Q31bFOS,Q31bWVT,Q31bGRN,Q31bSOC,Q32DISG,Q33cell,Q34RELIGIOUS,Q35ATEREL,Q41awge,Q41bbus,Q41cVOL,Q41dret,Q42asto,Q42bsp,Q43salc,Q44atm,Q44bmin,Q45sec,Q46alook,Q46bstart,Q46crnsw,Q46dAccJob,Q47jcr,undisab,disab,Sevdisab,Literacy3b,Stratum,GeoType,q42msal,Metro_code,Metro,employ_Status1,employ_Status2,rotation,person_wgt
0,160100720000002201,1,16010072000,1,1,1,48,10,2,1,6,8,88,2,2,8,88,2,2,8,88,3,8,8,8,1,2,3,2,2,1,2,9,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,5,1,2,2,9,660,1,99,2,1,1,9,9,99,9,2,0,0,0,0,10301,3,2640,1,2,1,1,3,827.480790
1,160100720000005901,1,16010072000,1,1,1,43,9,2,1,2,1,2,2,2,8,88,1,8,2,88,8,8,8,8,8,8,8,8,8,8,2,6,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,4,1,2,2,9,600,1,99,2,1,1,9,9,99,9,2,0,0,0,0,10301,3,2400,1,2,1,1,3,660.053718
2,160100720000005901,2,16010072000,1,1,2,42,9,2,2,2,1,1,2,2,8,88,2,2,8,88,7,8,8,8,8,8,8,8,8,8,2,9,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,4,2,2,2,2,888888888,8,88,88,8,8,2,2,88,8,2,0,0,0,0,10301,3,888888888,1,2,9,3,3,660.053718
3,160100720000013301,1,16010072000,1,1,1,54,11,2,1,2,1,2,2,2,8,88,2,2,8,88,9,8,8,8,8,8,8,8,8,8,2,2,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,5,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,8,1,1,1,1,1,1,2,2,2,2,1,2,1,2,1,2,2,2,2,2,2,1,2,1,5,2,2,2,2,888888888,8,88,88,8,8,2,2,88,8,2,0,0,0,0,10301,3,888888888,1,2,9,3,3,726.575927
4,160100720000013301,2,16010072000,1,1,2,36,8,2,2,2,1,1,1,8,2,88,1,8,2,88,8,8,8,8,8,8,8,8,8,8,2,2,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,1,1,1,1,1,9,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,5,1,2,2,9,500,1,99,2,1,1,9,9,99,9,2,0,0,0,0,10301,3,2000,1,2,1,1,3,726.575927

In [356]:
#code that reads in the data from 2016 and gives it the variable name, data_2016
data_2016 = pd.read_csv('/content/sample_data/ghs-2016-person-v1.csv', encoding = 'latin-1')
data_2016.head() #displays the first five rows of the dataset

,UqNr,PersonNR,PSU,Prov,B_Nights,Gender,Age,Age_grp1,Race,F_Linsidehh,F_Loutsidehh,Q11RELSH,Q12aMARST,Q12BSPOU,Q12CPSNN,Q13aFATH,Q13bFalive,Q13cFPAR,Q13dFPSN,Q14aMOTH,Q14bMalive,Q14cMPAR,Q14dMPSN,Q15HIEDU,Q16ATECHILD,Q16BNOTATTE,Q16CMAINREASN,Q16DFEES,Q16E1PICTURE,Q16E2TAP,Q16E3ELECTR,Q16E4FLUSHTOILET,Q16E5PITLAT,Q16E6TOYS,Q16E7FENCE,Q16E8PLAYAREA,Q16E9EQUIPMENT,Q16E10GADERN,Q17ATAKCARE,Q17BRELATIONSHP,Q18AIMITATE,Q18BOBJECT,Q18CREAD,Q18DSING,Q18ETALK,Q18FDISTRACT,Q18F2TALK,Q18F3SHOUT,Q18F4PUNISH,Q18F5ISOLATE,Q18F6NOTHING,Q18GBREASTFED,Q18HOTHERFOOD,Q18IMILK,Q18JEATFOOD,Q18KREG,Q18LPREPARED,Q19WRTN,Q19READ,Q19FORM,Q19WRTL,Q19CAL,Q19RDSN,Q110ATTE,Q111RSNN,Q112EDUI,Q113PPRIV,Q114DLRN,Q115aMOD,Q115bTIM,Q115cNR,Q115dNNI,Q116FEET,Q117RNFE,Q118BURS,Q119ALanguage,Q119AMathematics,Q119BTEXTBOOKS,Q119cBOOK,Q119cPOOR,Q119cLACK,Q119cBADC,Q119cFEES,Q119cCLAS,Q119cTABS,Q119cPMAN,Q119cOTHR,Q120GRDE,Q121SAME,Q122aFOOD,Q122bEFOOD,Q123aVIOL,Q123bVIOL1,Q123bVIOL2,Q123bVIOL3,Q123bVIOL4,Q123bVIOL5,Q123bVIOL6,Q124aABS,Q124bDAY,Q124cRSN,Q21MEDI,Q22GENHEALTH,Q23FLU,Q23DIA,Q23SCblood,Q23SUB,Q23DEP,Q23SEX,Q23PNEU,Q23BRON,Q23EPIL,Q24aCON,Q24bYNT,Q25aMVHoccupant,Q25aMVHpedestrian,Q25aBCL,Q25aGUN,Q25aSTR,Q25aCRIME,Q25aFIRE,Q25aACCP,Q25aINTP,Q25aSPORTS,Q25aDisability,Q25aOTH,Q25bmiss,Q26ASM,Q26DBT,Q26CAN,Q26HIV,Q26HBP,Q26RTH,Q26STRK,Q26HEART,Q26TB,Q26mental,Q26epil,Q26men,Q26pneu,Q26bron,Q26chole,Q26oster,Q26OTH,Q27aPRE,Q27bSTA,Q28APROV,Q28BBORN,Q28CDOCTOR,Q28CNURSE,Q28CTRADBIRTH,Q28CFAMILY,Q28CFATHER,Q28DBIRTHCERT,Q28ERECIEVDATE,Q28FAPPLIED,Q29SEE,Q29HEA,Q29WAL,Q29REM,Q29SEL,Q29COM,Q210EYE,Q210HAID,Q210WST,Q210WCH,Q210OTH,Q31asg,Q31bOAG,Q31bDIS,Q31bCSG,Q31bCAR,Q31bFOS,Q31bWVT,Q31bGRN,Q31bSOC,Q32DISG,Q33CELL,Q34BANK,Q34INVESTACC,Q34PENSION,Q34INFORMALSAV,Q34LAND,Q34THISDWELLING,Q34RESIDPROPERTY,Q41aWGE,Q41bBUS,Q41cVOL,Q41dRET,Q42aSTO,Q42bSP,Q43SALC,Q44aTM,Q44bMIN,Q45SEC,Q46aLOOK,Q46bSTART,Q46cRNSW,Q46dAccJob,Q47JCR,Q48RESP,undisab,disab,Sevdisab,Literacy3b,stratum,geotype,Q42msal,Metro_code,Metro,employ_Status1,employ_Status2,Rotation,person_wgt
0,160100720000002201,1,16010072000,1,1,1,49,10,2,1,1,1,2,1,2,1,8,2,88,3,8,8,88,2,88,8,88,8,8,8,8,8,8,8,8,8,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,4,4,4,4,4,1,2,1,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,88,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,3,2,3,3,3,3,3,1,2,2,9,751,1,99,2,1,1,9,9,99,9,2,1,0,0,0,1,10301,3,3004,1,2,1,1,3,1333.257200
1,160100720000002201,2,16010072000,1,1,2,54,11,2,1,1,2,2,1,1,2,2,8,88,2,2,8,88,7,88,8,88,8,8,8,8,8,8,8,8,8,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,1,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,9,9,88,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,3,3,3,3,3,3,3,1,2,2,9,690,1,99,2,1,1,9,9,99,9,2,1,0,0,0,0,10301,3,2760,1,2,1,1,3,1333.257200
2,160100720000002201,3,16010072000,1,1,2,25,6,2,1,1,3,7,8,88,2,2,8,88,1,8,1,2,9,88,8,88,8,8,8,8,8,8,8,8,8,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,10,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,88,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,3,3,3,3,3,3,3,1,2,2,9,500,1,99,2,1,1,9,9,99,9,2,3,0,0,0,0,10301,3,2000,1,2,1,1,3,1333.257200
3,160100720000002201,4,16010072000,1,1,1,1,1,2,1,1,9,7,8,88,1,8,2,88,1,8,1,3,98,6,2,2,8,8,8,8,8,8,8,8,8,8,8,3,1,4,4,2,2,3,1,1,2,2,2,2,1,1,1,9,9,9,8,8,8,8,8,8,8,88,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,1,2,1,1,2,2,2,1,2,2,8,8,8,8,8,8,8,8,8,8,8,2,8,8,8,8,8,8,8,8,8,2,3,3,3,3,3,3,3,8,8,8,8,888888888,8,88,88,8,8,8,8,88,8,8,3,0,0,0,0,10301,3,888888888,1,2,8,8,3,1333.257200
4,160100720000005901,1,16010072000,1,1,1,29,6,1,14,2,1,1,1,2,2,2,8,88,1,8,2,88,12,88,8,88,8,8,8,8,8,8,8,8,8,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,6,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,88,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,1,1,1,3,3,3,3,3,1,2,2,9,1500,1,99,2,1,1,9,9,99,9,2,1,0,0,0,0,10301,3,6000,1,2,1,1,3,1347.624634

In [357]:
#code that reads in the data from 2017 and gives it the variable name, data_2017
data_2017 = pd.read_csv('/content/sample_data/ghs-2017-person-1.0.csv', encoding = 'latin-1')
data_2017.head() #displays the first five rows of the dataset

,UqNr,PersonNR,PSU,Prov,B_Nights,Gender,Age,Age_grp1,Race,F_Linsidehh,F_Loutsidehh,Q11RELSH,Q12aMARST,Q12BSPOU,Q12CPSNN,Q13aFATH,Q13bFalive,Q13cFPAR,Q13dFPSN,Q14aMOTH,Q14bMalive,Q14cMPAR,Q14dMPSN,Q15HIEDU,Q16ATECHILD,Q16BNOTATTE,Q16CMAINREASN,Q17FEES,Q18READ,Q18STORIES,Q18SING,Q18DRAW,Q18TALK,Q18COUNT,Q18NAME,Q18PLAY,Q19WRTN,Q19READ,Q19FORM,Q19WRTL,Q19CAL,Q19RDSN,Q110ATTE,Q111RSNN,Q112EDUI,Q113PPRIV,Q114DLRN,Q115aMOD,Q115bTIM,Q115cNR,Q115dNNI,Q116FEET,Q117RNFE,Q118BURS,Q119ALanguage,Q119AMathematics,Q119BTEXTBOOKS,Q119cBOOK,Q119cPOOR,Q119cLACK,Q119cBADC,Q119cFEES,Q119cCLAS,Q119cTABS,Q119cPMAN,Q119cOTHR,Q120GRDE,Q121SAME,Q122aFOOD,Q122bEFOOD,Q123aVIOL,Q123bVIOL1,Q123bVIOL2,Q123bVIOL3,Q123bVIOL4,Q123bVIOL5,Q123bVIOL6,Q124aABS,Q124bDAY,Q124cRSN,Q21MEDI,Q22GENHEALTH,Q23FLU,Q23DIA,Q23SCblood,Q23SUB,Q23DEP,Q23SEX,Q23PNEU,Q23BRON,Q23EPIL,Q24aCON,Q24bYNT,Q25aMVHoccupant,Q25aMVHpedestrian,Q25aBCL,Q25aGUN,Q25aSTR,Q25aCRIME,Q25aFIRE,Q25aACCP,Q25aINTP,Q25aSPORTS,Q25aDisability,Q25aOTH,Q25bmiss,Q26ASM,Q26DBT,Q26CAN,Q26HIV,Q26HBP,Q26RTH,Q26STRK,Q26HEART,Q26TB,Q26mental,Q26epil,Q26men,Q26pneu,Q26bron,Q26chole,Q26oster,Q26OTH,Q27aPRE,Q27bSTA,Q28SEE,Q28HEA,Q28WAL,Q28REM,Q28SEL,Q28COM,Q29EYE,Q29HAID,Q29WST,Q29WCH,Q29OTH,Q31asg,Q31bOAG,Q31bDIS,Q31bCSG,Q31bCAR,Q31bFOS,Q31bWVT,Q31bGRN,Q31bSOC,Q32DISG,Q33CELL,Q34BANK,Q34INVESTACC,Q34PENSION,Q34INFORMALSAV,Q34LAND,Q34THISDWELLING,Q34RESIDPROPERTY,Q41aWGE,Q41bBUS,Q41cVOL,Q41dRET,Q42aSTO,Q42bSP,Q43SALC,Q44aTM,Q44bMIN,Q45SEC,Q46aLOOK,Q46bSTART,Q46cRNSW,Q46dAccJob,Q47JCR,Q48RESP,undisab,disab,Sevdisab,Literacy3b,stratum,geotype,Q42msal,Metro_code,Metro,employ_Status1,employ_Status2,Rotation,person_wgt
0,160100720000002201,1,16010072000,1,1,1,50,11,2,1,1,1,5,8,88,3,8,8,88,3,8,8,88,2,88,8,8,8,8,8,8,8,8,8,8,8,3,3,3,3,3,3,2,1,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,9,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,3,3,3,3,3,3,1,2,2,9,850,1,99,2,1,1,9,9,99,9,2,1,0,0,0,1,10301,3,3400,1,2,1,1,3,805.678067
1,160100720000005901,1,16010072000,1,1,1,29,6,1,14,2,1,2,1,2,2,2,8,88,1,8,2,88,11,88,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,1,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,9,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,1,3,3,3,3,3,3,3,1,2,2,9,2000,2,99,2,1,1,9,9,99,9,2,2,0,0,0,0,10301,3,2000,1,2,1,1,3,1546.103848
2,160100720000005901,2,16010072000,1,1,2,24,5,1,14,2,2,2,1,1,2,2,8,88,1,8,2,88,11,88,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,1,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,9,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,3,3,3,3,3,3,3,2,2,2,2,888888888,8,88,88,8,8,2,2,88,8,2,2,0,0,0,0,10301,3,888888888,1,2,9,3,3,1546.103848
3,160100720000005901,3,16010072000,1,1,2,0,1,1,14,2,3,7,8,88,1,8,1,1,1,8,1,2,98,6,1,9,0,3,1,1,3,3,2,2,1,8,8,8,8,8,8,8,88,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,1,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,9,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,9,9,8,8,8,8,8,8,8,8,8,8,8,2,8,8,8,8,8,8,8,8,8,2,3,3,3,3,3,3,3,8,8,8,8,888888888,8,88,88,8,8,8,8,88,8,8,2,0,0,0,0,10301,3,888888888,1,2,8,8,3,1546.103848
4,160101220000002601,1,16010122000,1,1,2,70,15,2,1,1,1,7,8,88,2,2,8,88,2,2,8,88,6,88,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,1,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,2,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,9,2,8,2,2,2,2,1,2,2,2,2,2,2,2,2,2,1,2,2,9,9,2,1,2,1,1,1,2,2,2,2,2,1,1,2,2,2,2,2,2,2,8,2,3,3,3,3,3,1,3,2,2,2,2,888888888,8,88,88,8,8,2,2,88,8,2,1,1,1,0,0,10103,1,888888888,1,2,9,3,1,500.202505

In [358]:
#code that reads in the data from 2018 and gives it the variable name, data_2018
data_2018 = pd.read_csv('/content/sample_data/ghs-2018-person-v1.csv', encoding = 'latin-1')
data_2018.head() #displays the first five rows of the dataset

,UqNr,PersonNR,PSU,Prov,B_Nights,Gender,Age,Age_grp1,Race,F_Linsidehh,F_Loutsidehh,Q11RELSH,Q12aMARST,Q12BSPOU,Q12CPSNN,Q13aFATH,Q13bFalive,Q13cFPAR,Q13dFPSN,Q14aMOTH,Q14bMalive,Q14cMPAR,Q14dMPSN,Q15HIEDU,Q16ATECHILD,Q16BNOTATTE,Q16CMAINREASN,Q17FEES,Q18READ,Q18STORIES,Q18SING,Q18DRAW,Q18TALK,Q18COUNT,Q18NAME,Q18PLAY,Q19WRTN,Q19READ,Q19FORM,Q19WRTL,Q19CAL,Q19RDSN,Q110ATTE,Q111RSNN,Q112EDUI,Q113PPRIV,Q114DLRN,Q115aMOD,Q115bTIM,Q115cNR,Q115dNNI,Q116FEET,Q117RNFE,Q118BURS,Q119ALanguage,Q119AMathematics,Q119BTEXTBOOKS,Q119cBOOK,Q119cPOOR,Q119cLACK,Q119cBADC,Q119cFEES,Q119cCLAS,Q119cTABS,Q119cPMAN,Q119cOTHR,Q120GRDE,Q121SAME,Q122aFOOD,Q122bEFOOD,Q123aVIOL,Q123bVIOL1,Q123bVIOL2,Q123bVIOL3,Q123bVIOL4,Q123bVIOL5,Q123bVIOL6,Q124aABS,Q124bDAY,Q124cRSN,Q21MEDI,Q22GENHEALTH,Q23FLU,Q23DIA,Q23SCblood,Q23SUB,Q23DEP,Q23SEX,Q23PNEU,Q23BRON,Q23EPIL,Q23MAL,Q24aCON,Q24bYNT,Q25aMVHoccupant,Q25aMVHpedestrian,Q25aBCL,Q25aGUN,Q25aSTR,Q25aCRIME,Q25aFIRE,Q25aACCP,Q25aINTP,Q25aSPORTS,Q25aDisability,Q25aOTH,Q25bmiss,Q26ASM,Q26DBT,Q26CAN,Q26HIV,Q26HBP,Q26RTH,Q26STRK,Q26HEART,Q26TB,Q26mental,Q26epil,Q26MAL,Q26men,Q26pneu,Q26bron,Q26chole,Q26oster,Q26OTH,Q27aPRE,Q27bSTA,Q28SEE,Q28HEA,Q28WAL,Q28REM,Q28SEL,Q28COM,Q29EYE,Q29HAID,Q29WST,Q29WCH,Q29OTH,Q31asg,Q31bOAG,Q31bDIS,Q31bCSG,Q31bCAR,Q31bFOS,Q31bWVT,Q31bGRN,Q31bSOC,Q32DISG,Q33CELL,Q34BANK,Q34INVESTACC,Q34PENSION,Q34INFORMALSAV,Q34LAND,Q34THISDWELLING,Q34RESIDPROPERTY,Q41aWGE,Q41bBUS,Q41cVOL,Q41dRET,Q42aSTO,Q42bSP,Q43SALC,Q44aTM,Q44bMIN,Q45SEC,Q46aLOOK,Q46bSTART,Q46cRNSW,Q46dAccJob,Q47JCR,Q48RESP,undisab,disab,Sevdisab,Literacy3b,stratum,geotype,Q42msal,Metro_code,Metro,employ_Status1,employ_Status2,Rotation,person_wgt
0,160100720000002201,1,16010072000,1,1,1,19,4,2,1,1,1,7,8,88,1,8,2,88,1,8,2,88,8,88,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,6,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,1,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,3,3,3,3,3,3,1,2,2,9,2900,2,99,2,1,1,9,9,99,9,2,1,0,0,0,0,10301,3,2900,1,2,1,1,3,974.509552
1,160100720000005901,1,16010072000,1,1,1,31,7,1,9,2,1,2,1,2,2,2,8,88,1,8,2,88,11,88,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,1,2,3,3,3,3,3,3,1,2,2,9,3120,1,99,2,1,1,9,9,99,9,2,2,0,0,0,0,10301,3,12480,1,2,1,1,3,1896.300138
2,160100720000005901,2,16010072000,1,1,2,25,6,1,9,2,2,2,1,1,2,2,8,88,1,8,2,88,11,88,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,1,1,1,1,1,1,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,1,2,3,3,3,3,3,3,1,2,2,9,2240,1,99,2,1,1,9,9,99,9,2,2,0,0,0,0,10301,3,8960,1,2,1,1,3,1896.300138
3,160100720000005901,3,16010072000,1,1,2,1,1,1,9,2,3,7,8,88,9,9,9,99,9,9,9,99,98,3,9,8,0,2,1,1,2,1,1,1,1,8,8,8,8,8,8,8,88,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,9,9,8,8,8,8,8,8,8,8,8,8,8,2,8,8,8,8,8,8,8,8,8,2,3,3,3,3,3,3,3,8,8,8,8,888888888,8,88,88,8,8,8,8,88,8,8,2,0,0,0,0,10301,3,888888888,1,2,8,8,3,1896.300138
4,160101220000002601,1,16010122000,1,1,2,71,15,2,1,1,1,7,8,88,2,2,8,88,2,2,8,88,7,88,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,1,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,4,2,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,9,9,1,1,1,1,1,1,2,2,2,2,2,1,1,2,2,2,2,2,2,2,8,2,3,3,3,3,3,1,3,2,2,2,2,888888888,8,88,88,8,8,2,2,88,8,2,1,0,0,0,0,10103,1,888888888,1,2,9,3,1,702.936011

In [359]:
#code that reads in the data from 2019 and gives it the variable name, data_2019
data_2019 = pd.read_csv('/content/sample_data/ghs-2019-person-v1.csv', encoding = 'latin-1')
data_2019.head() #displays the first five rows of the dataset

<ipython-input-359-26f19e2eec7b>:2: DtypeWarning: Columns (137) have mixed types. Specify dtype option on import or set low_memory=False.
  data_2019 = pd.read_csv('/content/sample_data/ghs-2019-person-v1.csv', encoding = 'latin-1')

,uqnr,personnr,psu,prov,Four_by_Four,Sex,age,age_grp1,Population,HHC_RELATIONSHIP,HHC_MARITAL,SPOUSE,SPOUSE_NAME,HHC_FATH_ALIVE,HHC_FATH_PARTHH,HHC_FATH_NAME,HHC_MOTH_ALIVE,HHC_MOTH_PARTHH,HHC_MOTH_NAME,Education,ECD_CHLDATT,ECD_NOTATT,ECD_NOTATT_RSN,ECD_FEES,EDU_WRTN,EDU_READ,EDU_FORM,EDU_WRTL,EDU_CAL,EDU_RDSN,EDU_ATTEND,EDU_RSNN,EDU_EDUI,EDU_PPRIV,EDU_CORR,EDU_MODE_TR,EDU_TIME,EDU_NEAREST,EDU_NOTNEAR,EDU_BURS,EDU_TOTFEES,EDU_NOFEES,EDU_GRDE,EDU_PROB_BOOK,EDU_PROB_POOR,EDU_PROB_LACK,EDU_PROB_BADC,EDU_PROB_FEES,EDU_PROB_CLAS,EDU_PROB_TABS,EDU_PROB_TSTR,EDU_FOOD,EDU_EATFOOD,EDU_VLNC,EDU_VLNC_CORP,EDU_VLNC_PHYT,EDU_VLNC_VERT,EDU_VLNC_VERL,EDU_VLNC_PHYL,EDU_ABS,EDU_ABS_DAYS,EDU_ABS_RSN,HLT_MEDI,HLT_GENHEALTH,HLT_ILLNESS_FLU,HLT_ILLNESS_DIA,HLT_ILLNESS_SCBLOOD,HLT_ILLNESS_SUB,HLT_ILLNESS_DEP,HLT_ILLNESS_STD,HLT_ILLNESS_PNEU,HLT_ILLNESS_BRON,HLT_ILLNESS_EPIL,HLT_ILLNESS_MAL,HLT_CONSULT,HLT_CONSULT_YNOT,HLT_INJPOIS,HLT_INJPOIS_MVOC,HLT_INJPOIS_MVPE,HLT_INJPOIS_BICY,HLT_INJPOIS_GUN,HLT_INJPOIS_STVIOL,HLT_INJPOIS_CRIME,HLT_INJPOIS_FIRE,HLT_INJPOIS_ACCPOIS,HLT_INJPOIS_INTPOIS,HLT_INJPOIS_SPORTS,HLT_INJPOIS_MTCY,HLT_INJPOIS_OTHER,HLT_days_MISS,HLT_CHRONIC_ASM,HLT_CHRONIC_DBT,HLT_CHRONIC_CAN,HLT_CHRONIC_HIV,HLT_CHRONIC_HBP,HLT_CHRONIC_ARTH,HLT_CHRONIC_STRK,HLT_CHRONIC_HEART,HLT_CHRONIC_TB,HLT_CHRONIC_MENTAL,HLT_CHRONIC_EPIL,HLT_CHRONIC_MEN,HLT_CHRONIC_PNEU,HLT_CHRONIC_BRON,HLT_CHRONIC_OSTER,HLT_CHRONIC_MAL,HLT_PREG,HLT_CHRONIC_CHOLE,HLT_PREGSTAT,DSB_SEE,DSB_HEA,DSB_WAL,DSB_REM,DSB_SEL,DSB_COM,DSB_ASTD_EYEGLASS,DSB_ASTD_HEARAID,DSB_ASTD_WALKSTICK,DSB_ASTD_WHECHAIR,DSB_ASTD_OTHER,SOC_GRANT,SOC_GRANT_TYPE,SOC_DISB_PERM,ITP_CELL,LAB_WGE,LAB_BUS,LAB_VOL,LAB_RET,LAB_AMOUNT,LAB_STO,LAB_SALPER,LAB_SALC,LAB_TRANSP,LAB_MINS,LAB_SECTOR,LAB_LOOK,LAB_GOVPROG,LAB_RES_NAME,undisab,disab,sevdisab,literacy3b,Stratum,geotype,LAB_SALARY,metro_code,metro,Rotation,person_wgt
0,160100090000003901,1,16010009000,Western Cape,Yes,Male,76,75+,White,Head/acting head,Legally married,No,Not applicable,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No difficulty,No difficulty,Some difficulty,No difficulty,Some difficulty,No difficulty,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Fair,Yes,No,No,No,No,No,No,No,No,No,No,Not necessary/the problem was not serious enough,No,No,No,No,No,No,No,No,No,No,No,No,No,Not applicable,No,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,Not applicable,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,Yes,No,No,No,No,No,Not applicable,Not applicable,Yes,Yes,Yes,No,Not applicable,No,Do not know,Not applicable,14,Walking,Less than 15 minutes,In the formal sector (registered to perform ac...,Not applicable,No,1,Not disabled,Not disabled,Not disabled,Literate,10301,3,Not applicable,WC  Non-metro,Non-metro,Quarter 3,680.176463
1,160100090000003901,2,16010009000,Western Cape,Yes,Female,73,7074 years,White,Husband/wife/partner of household head,Legally married,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 10/Standard 8/Form 3/NCV Level 2/Occupat...,Not applicable,Not applicable,Not applicable,Not applicable,Some difficulty,Some difficulty,Some difficulty,Some difficulty,Some difficulty,Some difficulty,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Fair,No,No,No,No,No,No,No,No,No,No,Not applicable,Not applicable,No,No,No,No,No,No,No,No,No,No,No,No,No,Not applicable,Yes,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Unspecified,No,Not applicable,Some difficulty,Some difficulty,A lot of difficulty,No difficulty,Some difficulty,No difficulty,Yes,No,No,No,No,No,Not applicable,Not applicable,No,No,No,No,No,Do not know,Do not know,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,1,Disabled,Disabled,Disabled,Literate,10301,3,Not applicable,WC  Non-metro,Non-metro,Quarter 3,680.176463
2,160100090000007201,1,16010009000,Western Cape,Yes,Male,57,5559 years,Coloured,Head/acting head,Legally married,Yes,2,Yes,No,Not applicable,No,Not applicable,Not applicable,No schooling,Not applicable,Not applicable,Not applicable,Not applicable,A lot of difficulty,A lot of difficulty,A lot of difficulty,A lot of difficulty,A lot of difficulty,Some difficulty,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Good,Yes,No,No,No,No,No,No,No,No,No,No,Not necessary/the problem was not serious enough,No,No,No,No,No,No,No,No,No,No,No,No,No,Not applicable,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Not applicable,No,Not applicable,Some difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,Yes,No,No,No,No,No,Not applicable,Not applicable,Yes,Yes,No,No,Not applicable,No,Do not know,Not applicable,8,Walking,Less than 15 minutes,In the formal sector (registered to perform ac...,Not applicable,No,2,Not disabled,Disabled,Not disabled,Illiterate,10301,3,5300,WC  Non-metro,Non-metro,Quarter 3,572.047242
3,160100090000007201,2,16010009000,Western Cape,Yes,Female,57,5559 years,Coloured,Husband/wife/partner of household head,Legally married,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 8/Standard 6/Form 1,Not applicable,Not applicable,Not applicable,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Good,Yes,No,No,No,No,No,No,No,No,No,Yes,Not applicable,No,No,No,No,No,No,No,No,No,No,No,No,No,Not applicable,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Unspecified,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,Yes,Disability grant,Temporary disability,Yes,No,No,No,No,Do not know,Do not know,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,2,Not disabled,Not disabled,Not disabled,Literate,10301,3,Not applicable,WC  Non-metro,Non-metro,Quarter 3,572.047242
4,160100090000007201,3,16010009000,Western Cape,Yes,Female,26,2529 years,Coloured,Son/daughter/stepchild/adopted child of househ...,Single and have never been married/never lived...,Not applicable,Not applicable,Yes,Yes,1,Yes,Yes,2,Grade 10/Standard 8/Form 3/NCV Level 2/Occupat...,Not applicable,Not applicable,Not applicable,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Has completed education/satisfied with my leve...,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Excellent,No,No,No,No,No,No,No,No,No,No,Not applicable,Not applicable,No,No,No,No,No,No,No,No,No,No,No,No,No,Not applicable,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,No,No,No,No,No,Not applicable,Not applicable,Yes,Yes,No,No,Not applicable,Yes,3264,Per week,Not applicable,Walking,Less than 15 minutes,In the formal sector (registered to perform ac...,Not applicable,No,2,Not disabled,Not disabled,Not disabled,Literate,10301,3,13056,WC  Non-metro,Non-metro,Quarter 3,572.047242

In [360]:
#code that reads in the data from 2020 and gives it the variable name, data_2020
data_2020 = pd.read_csv('/content/sample_data/ghs-2020-person-v1.csv', encoding = 'latin-1')
data_2020.head() #displays the first five rows of the dataset

,uqnr,personnr,psu,prov,Four_by_Four,Sex,age,age_grp1,Population,hhc_relationship,hhc_marital,spouse,spouse_name,hhc_fath_alive,hhc_fath_parthh,hhc_fath_name,hhc_moth_alive,hhc_moth_parthh,hhc_moth_name,education,ecd_chldatt,ecd_notatt,ecd_notatt_rsn,ecd_fees,edu_attend,edu_edui,edu_ppriv,edu_corr,edu_homesch,edu_homesch_part,edu_homesch_smrtphone,edu_homesch_computer,edu_homesch_tablet,edu_burs,edu_totfees,edu_nofees,edu_grde,edu_food,edu_eatfood,hlt_medi,hlt_covid_postest,hlt_chronic_asm,hlt_chronic_dbt,hlt_chronic_hbp,hlt_chronic_strk,hlt_chronic_tb,dsb_see,dsb_hea,dsb_wal,dsb_rem,dsb_sel,dsb_com,soc_grant,soc_grant_oag,soc_grant_dis,soc_grant_csg,soc_grant_car,soc_grant_fos,soc_grant_wvt,soc_grant_grn,soc_grant_srd,lab_wge,lab_bus,lab_vol,lab_ret,lab_amount,lab_sto,lab_salper,lab_salc,lab_look,lab_start,lab_rnsw,undisab,disab,sevdisab,stratum,geotype,lab_salary,metro,rotation,person_wgt
0,160100090000003901,1,16010009000,Western Cape,Yes,Male,77,75+,White,Head/acting head,Legally married,Yes,2,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,No,Yes,No,No,No difficulty,No difficulty,Some difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Yes,No,Not applicable,No,Do not know,Not applicable,15,Not applicable,Not applicable,Not applicable,Not disabled,Disabled,Not disabled,10301,3,Unspecified,Non-metro,Quarter 3,2897.433413
1,160100090000003901,2,16010009000,Western Cape,Yes,Female,75,75+,White,Husband/wife/partner of household head,Legally married,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 10/Standard 8/Form 3/NCV Level 2/Occupat...,Not applicable,Not applicable,Not applicable,Not applicable,No,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,Yes,Yes,No,No,A lot of difficulty,No difficulty,A lot of difficulty,Some difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,Do not know,Not applicable,Not applicable,No,No,Not applicable,Disabled,Disabled,Disabled,10301,3,Not applicable,Non-metro,Quarter 3,2802.173697
2,160100330000006101,1,16010033000,Western Cape,Yes,Male,69,65-69,White,Head/acting head,Legally married,Yes,2,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,Yes,No,No,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,Do not know,Not applicable,Not applicable,No,No,Not applicable,Not disabled,Not disabled,Not disabled,10107,1,Not applicable,Non-metro,Quarter 4,1894.711557
3,160100330000006101,2,16010033000,Western Cape,Yes,Female,63,60-64,White,Husband/wife/partner of household head,Legally married,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,No,No,No,No,Some difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,Do not know,Not applicable,Not applicable,No,No,Not applicable,Not disabled,Disabled,Not disabled,10107,1,Not applicable,Non-metro,Quarter 4,1859.272011
4,160100330000006101,3,16010033000,Western Cape,Yes,Female,71,70-74,White,Other relative (e.g. in-laws or aunt/uncle) of...,Divorced,Not applicable,Not applicable,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Do not know,No,No,No,No,No,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,Do not know,Not applicable,Not applicable,No,No,Not applicable,Not disabled,Not disabled,Not disabled,10107,1,Not applicable,Non-metro,Quarter 4,1955.061926

In [361]:
#code that reads in the data from 2021 and gives it the variable name, data_2021
data_2021 = pd.read_csv('/content/sample_data/ghs-2021-person-v1.csv', encoding = 'latin-1')
data_2021.head() #displays the first five rows of the dataset

,uqnr,personnr,psu,prov,Four_by_Four,Sex,age,age_grp1,Population,hhc_relationship,hhc_marital,spouse,spouse_name,hhc_fath_alive,hhc_fath_parthh,hhc_fath_name,hhc_moth_alive,hhc_moth_parthh,hhc_moth_name,education,ecd_chldatt,ecd_notatt,ecd_notatt_rsn,ecd_fees,edu_attend,edu_rsnn,edu_edui,edu_ppriv,edu_corr,edu_homesch,edu_attfreq,edu_homesch_part,edu_homesch_smrtphone,edu_homesch_computer,edu_homesch_tablet,edu_homesch_printed,edu_burs,edu_totfees,edu_nofees,edu_grde,edu_same,edu_food,edu_eatfood,hlt_medi,hlt_covid_postest,hlt_chronic_asm,hlt_chronic_dbt,hlt_chronic_hbp,hlt_chronic_strk,hlt_preg,hlt_chronic_tb,dsb_see,dsb_hea,dsb_wal,dsb_rem,dsb_sel,dsb_com,soc_grant,soc_grant_oag,soc_grant_dis,soc_grant_csg,soc_grant_car,soc_grant_fos,soc_grant_wvt,soc_grant_grn,soc_grant_srd,lab_wge,lab_bus,lab_vol,lab_ret,lab_amount,lab_sto,lab_salper,lab_salc,lab_look,lab_start,lab_rnsw,lab_accjob,undisab,disab,sevdisab,stratum,geotype,lab_salary,employ_Status1,employ_Status2,metro,metro_code,rotation,person_wgt
0,160100090000003901,1,16010009000,Western Cape,Yes,Male,78,75+,White,Head/acting head,Legally married,Yes,2,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Yes,No,Not applicable,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Yes,No,Not applicable,No,DO NOT KNOW:,Not applicable,15,Not applicable,Not applicable,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10301,3,Unspecified,Employed,Employed,Non-metro,WC - Non-metro,Quarter 3,2970.762309
1,160100090000003901,2,16010009000,Western Cape,Yes,Female,75,75+,White,Husband/wife/partner of household head,Legally married,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 10/Standard 8/Form 3/NCV Level 2/Occupat...,Not applicable,Not applicable,Not applicable,Not applicable,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,Yes,Yes,No,Not applicable,No,A lot of difficulty,No difficulty,A lot of difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,DO NOT KNOW:,Not applicable,Not applicable,No,No,Not applicable,Not applicable,Disabled,Disabled,Disabled,10301,3,Not applicable,Unspecified,Not economically active,Non-metro,WC - Non-metro,Quarter 3,2971.535495
2,160100630000010801,1,16010063000,Western Cape,Yes,Female,28,25-29,Coloured,Head/acting head,Living together like husband and wife/partners,Yes,2,Yes,No,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,No,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,Not applicable,No,DO NOT KNOW:,Not applicable,7,Not applicable,Not applicable,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10106,1,4017,Employed,Employed,Non-metro,WC - Non-metro,Quarter 3,5611.998377
3,160100630000010801,2,16010063000,Western Cape,Yes,Male,40,40-44,Coloured,Husband/wife/partner of household head,Living together like husband and wife/partners,Yes,1,No,Not applicable,Not applicable,Yes,No,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,Not applicable,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,Not applicable,No,DO NOT KNOW:,Not applicable,14,Not applicable,Not applicable,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10106,1,2029,Employed,Employed,Non-metro,WC - Non-metro,Quarter 3,5585.705994
4,160100630000010801,3,16010063000,Western Cape,Yes,Female,17,15-19,Coloured,Son/daughter/stepchild/adopted child of househ...,Single and have never been married/never lived...,Not applicable,Not applicable,Yes,No,Not applicable,Yes,Yes,Unspecified,Grade 8/Standard 6/Form 1,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Not applicable,School (including Grade R to Grade 12 learners...,Public (Government),No,No,Four days,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,NaN,No fee school (School does not ask for tuition...,Grade 9,No,Yes,"Yes, a few times a week",No,No,No,No,No,No,No,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,DO NOT KNOW:,Not applicable,Not applicable,No,No,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10106,1,Not applicable,Unspecified,Not economically active,Non-metro,WC - Non-metro,Quarter 3,5595.212493

In [362]:
#code that reads in the data from 2022 and gives it the variable name, data_2022
data_2022 = pd.read_csv('/content/sample_data/ghs-2022-person-v1.csv', encoding = 'latin-1')
data_2022.head() #displays the first five rows of the dataset

,uqnr,personnr,psu,prov,Four_by_Four,Sex,age,age_grp1,Population,Languages,hhc_relationship,hhc_marital,spouse,spouse_name,hhc_fath_alive,hhc_fath_parthh,hhc_fath_name,hhc_moth_alive,hhc_moth_parthh,hhc_moth_name,education,ecd_chldatt,ecd_notatt,ecd_notatt_rsn,ecd_fees,ecd_read,ecd_sing,ecd_colour,ecd_object,ecd_count,ecd_play,edu_attend,edu_rsnn,edu_edui,edu_ppriv,edu_corr,edu_mode_tr,edu_time,edu_burs,edu_totfees,edu_nofees,edu_grde,edu_same,edu_food,edu_eatfood,edu_vlnc,edu_vlnc_corp,edu_vlnc_phyt,edu_vlnc_vert,edu_vlnc_verl,edu_vlnc_phyl,edu_abs,edu_abs_days,edu_abs_rsn,hlt_medi,hlt_genhealth,hlt_vacci,hlt_chronic_asm,hlt_chronic_dbt,hlt_chronic_can,hlt_chronic_HIV,hlt_chronic_hbp,hlt_chronic_arth,hlt_chronic_strk,hlt_chronic_tb,hlt_chronic_broncho,hlt_chronic_covid,hlt_preg,dsb_see,dsb_hea,dsb_wal,dsb_rem,dsb_sel,dsb_com,soc_grant,soc_grant_oag,soc_grant_dis,soc_grant_csg,soc_grant_car,soc_grant_fos,soc_grant_grn,soc_grant_srd,Itp_cell,Itp_cell_sphone,lab_wge,lab_bus,lab_vol,lab_ret,lab_amount,lab_sto,lab_salper,lab_salc,lab_transp,lab_mins,lab_sector,lab_look,lab_start,lab_rnsw,lab_accjob,lab_res_name,undisab,disab,sevdisab,geotype,metro_code,metro,stratum,lab_salary,employ_Status1,employ_Status2,rotation,person_wgt
0,160100090000003901,1,16010009000,Western Cape,Yes,Male,79,75+,White,Afrikaans,Head/acting head,Legally married,Yes,2,No,Not applicable,Not applicable,No,Not applicable,Not applicable,GRADE 12/STANDARD 10/FORM 5/NATIONAL SENIOR CE...,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Has completed education/satisfied with my leve...,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Good,No,No,No,No,No,No,No,No,No,No,No,Not applicable,Some difficulty,No difficulty,Some difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Yes,No,Yes,No,Not applicable,No,Not applicable,Not applicable,REFUSED,Own car/other private vehicle/company vehicle,Less than 15 minutes,In the formal sector (registered to perform an...,Not applicable,Not applicable,Not applicable,Not applicable,2,Disabled,Disabled,Not disabled,3,WC  Non-metro,Non-metro,10301,Unspecified,Employed,Employed,Quarter 3,638.501583
1,160100090000003901,2,16010009000,Western Cape,Yes,Female,76,75+,White,Afrikaans,Husband/wife/partner of household head,Legally married,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,GRADE 10/STANDARD 8/FORM 3/NCV LEVEL 2/OCCUPAT...,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Too old/young,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Fair,No,No,Yes,No,No,Yes,No,No,No,No,No,Not applicable,Some difficulty,Some difficulty,Some difficulty,Some difficulty,Some difficulty,Some difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Not applicable,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,Not applicable,Not applicable,2,Disabled,Disabled,Not disabled,3,WC  Non-metro,Non-metro,10301,Not applicable,Unspecified,Not economically active,Quarter 3,638.501583
2,160100090000007201,1,16010009000,Western Cape,Yes,Male,31,30-34,Coloured,Afrikaans,Head/acting head,Living together like husband and wife/partners,Yes,2,Yes,No,Not applicable,Yes,No,Not applicable,GRADE 10/STANDARD 8/FORM 3/NCV LEVEL 2/OCCUPAT...,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Has completed education/satisfied with my leve...,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Good,"Yes, fully vaccinated with booster shot",No,No,No,No,No,No,No,No,No,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Yes,Yes,No,No,Not applicable,No,Not applicable,Not applicable,R42 001R54 000,Walking,Less than 15 minutes,In the formal sector (registered to perform an...,Not applicable,Not applicable,Not applicable,Not applicable,2,Not disabled,Not disabled,Not disabled,3,WC  Non-metro,Non-metro,10301,3929,Employed,Employed,Quarter 3,1302.069729
3,160100090000007201,2,16010009000,Western Cape,Yes,Female,34,30-34,Coloured,Afrikaans,Husband/wife/partner of household head,Living together like husband and wife/partners,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,GRADE 12/STANDARD 10/FORM 5/NATIONAL SENIOR CE...,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Has completed education/satisfied with my leve...,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Very good,"Yes, fully vaccinated with booster shot",No,No,No,No,No,No,No,No,No,No,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Yes,No,No,No,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Not applicable,Not applicable,No,2,Not disabled,Not disabled,Not disabled,3,WC  Non-metro,Non-metro,10301,Not applicable,Unspecified,Not economically active,Quarter 3,1302.069729
4,160100090000007201,3,16010009000,Western Cape,Yes,Male,12,10-14,Coloured,Afrikaans,Son/daughter/stepchild/adopted child of househ...,Single and have never been married/never lived...,Not applicable,Not applicable,Yes,Yes,1,Yes,Yes,2,GRADE 5/STANDARD 3/ABET/AET 2,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Not applicable,School (including Grade R to Grade 12 learners...,Public (government),No,Minibus/bus provided by institution/government...,1530 minutes,No,NONE,No fee school/school did not ask for fees,Grade 6,No,No,Not applicable,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,"Not applicable  school closed, e.g. school ho...",Not applicable,Not applicable,No,Very good,No,No,No,No,No,No,No,No,No,No,No,Not applicable,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,Yes,No,No,Yes,No,No,No,No,Yes,Yes,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Unspecified,Not disabled,Not disabled,Not disabled,3,WC  Non-metro,Non-metro,10301,Not applicable,Not applicable,Not applicable,Quarter 3,1302.069729

Now that we have an idea of how each dataset looks and that the variable of interest is Employment Status, we are now going to check which datasets contain tthe columns, 'employ_Status1' and 'employ_Status2'.

In [363]:
all_datasets = [data_2012, data_2013, data_2014, data_2015, data_2016, data_2017, data_2018, data_2019, data_2020, data_2021, data_2022]
dataset_names = ['2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021','2022']

In [364]:
def check_column_availability(datasets, target_column):
    availability_dict = {}

    for dataset, dataset_name in zip(datasets, dataset_names):
        availability_dict[dataset_name] = target_column in dataset.columns

    return availability_dict

# Example usage:
column_to_check = 'employ_Status1'  # Replace with the actual column name
availability_result = check_column_availability(all_datasets, column_to_check)

# Display the results
for dataset_name, is_available in availability_result.items():
    print(f"{dataset_name}: {column_to_check} {'is' if is_available else 'is not'} available.")

2012: employ_Status1 is not available.
2013: employ_Status1 is not available.
2014: employ_Status1 is available.
2015: employ_Status1 is available.
2016: employ_Status1 is available.
2017: employ_Status1 is available.
2018: employ_Status1 is available.
2019: employ_Status1 is not available.
2020: employ_Status1 is not available.
2021: employ_Status1 is available.
2022: employ_Status1 is available.

The datasets that do not contain the column, 'employ_Status1' are from 2012, 2013, 2019, and 2020. Now we check for 'employ_Status2'.

In [365]:
def check_column_availability(datasets, target_column):
    availability_dict = {}

    for dataset, dataset_name in zip(datasets, dataset_names):
        availability_dict[dataset_name] = target_column in dataset.columns

    return availability_dict

# Example usage:
column_to_check = 'employ_Status2'  # Replace with the actual column name
availability_result = check_column_availability(all_datasets, column_to_check)

# Display the results
for dataset_name, is_available in availability_result.items():
    print(f"{dataset_name}: {column_to_check} {'is' if is_available else 'is not'} available.")

2012: employ_Status2 is not available.
2013: employ_Status2 is not available.
2014: employ_Status2 is available.
2015: employ_Status2 is available.
2016: employ_Status2 is available.
2017: employ_Status2 is available.
2018: employ_Status2 is available.
2019: employ_Status2 is not available.
2020: employ_Status2 is not available.
2021: employ_Status2 is available.
2022: employ_Status2 is available.

The same datasets that do not contain 'employ_Status1' also do not contain 'employ_Status2'. We are not going to work with those datasets. We are now going to explore the relevant datasets.

In [366]:
data_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92459 entries, 0 to 92458
Columns: 183 entries, uqnr to person_wgt
dtypes: float64(1), int64(182)
memory usage: 129.1 MB

In [367]:
data_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74449 entries, 0 to 74448
Columns: 183 entries, uqnr to person_wgt
dtypes: float64(1), int64(182)
memory usage: 103.9 MB

In [368]:
data_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72602 entries, 0 to 72601
Columns: 214 entries, UqNr to person_wgt
dtypes: float64(1), int64(213)
memory usage: 118.5 MB

In [369]:
data_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72291 entries, 0 to 72290
Columns: 183 entries, UqNr to person_wgt
dtypes: float64(1), int64(182)
memory usage: 100.9 MB

In [370]:
data_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71137 entries, 0 to 71136
Columns: 185 entries, UqNr to person_wgt
dtypes: float64(1), int64(184)
memory usage: 100.4 MB

In [371]:
data_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35265 entries, 0 to 35264
Data columns (total 90 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   uqnr                   35265 non-null  int64
 1   personnr               35265 non-null  int64
 2   psu                    35265 non-null  int64
 3   prov                   35265 non-null  object
 4   Four_by_Four           35265 non-null  object
 5   Sex                    35265 non-null  object
 6   age                    35265 non-null  int64
 7   age_grp1               35265 non-null  object
 8   Population             35265 non-null  object
 9   hhc_relationship       35265 non-null  object
 10  hhc_marital            35265 non-null  object
 11  spouse                 35265 non-null  object
 12  spouse_name            35265 non-null  object
 13  hhc_fath_alive         35265 non-null  object
 14  hhc_fath_parthh        35265 non-null  object
 15  hhc_fath_name          35265 non-null  object
 16  hhc_moth_alive         35265 non-null  object
 17  hhc_moth_parthh        35265 non-null  object
 18  hhc_moth_name          35265 non-null  object
 19  education              35265 non-null  object
 20  ecd_chldatt            35265 non-null  object
 21  ecd_notatt             35265 non-null  object
 22  ecd_notatt_rsn         35265 non-null  object
 23  ecd_fees               34250 non-null  object
 24  edu_attend             35265 non-null  object
 25  edu_rsnn               35265 non-null  object
 26  edu_edui               35265 non-null  object
 27  edu_ppriv              35265 non-null  object
 28  edu_corr               35265 non-null  object
 29  edu_homesch            35265 non-null  object
 30  edu_attfreq            35265 non-null  object
 31  edu_homesch_part       35265 non-null  object
 32  edu_homesch_smrtphone  35265 non-null  object
 33  edu_homesch_computer   35265 non-null  object
 34  edu_homesch_tablet     35265 non-null  object
 35  edu_homesch_printed    35265 non-null  object
 36  edu_burs               35265 non-null  object
 37  edu_totfees            27571 non-null  object
 38  edu_nofees             35265 non-null  object
 39  edu_grde               35265 non-null  object
 40  edu_same               35265 non-null  object
 41  edu_food               35265 non-null  object
 42  edu_eatfood            35265 non-null  object
 43  hlt_medi               35265 non-null  object
 44  hlt_covid_postest      35265 non-null  object
 45  hlt_chronic_asm        35265 non-null  object
 46  hlt_chronic_dbt        35265 non-null  object
 47  hlt_chronic_hbp        35265 non-null  object
 48  hlt_chronic_strk       35265 non-null  object
 49  hlt_preg               35265 non-null  object
 50  hlt_chronic_tb         35265 non-null  object
 51  dsb_see                35265 non-null  object
 52  dsb_hea                35265 non-null  object
 53  dsb_wal                35265 non-null  object
 54  dsb_rem                35265 non-null  object
 55  dsb_sel                35265 non-null  object
 56  dsb_com                35265 non-null  object
 57  soc_grant              35265 non-null  object
 58  soc_grant_oag          35265 non-null  object
 59  soc_grant_dis          35265 non-null  object
 60  soc_grant_csg          35265 non-null  object
 61  soc_grant_car          35265 non-null  object
 62  soc_grant_fos          35265 non-null  object
 63  soc_grant_wvt          35265 non-null  object
 64  soc_grant_grn          35265 non-null  object
 65  soc_grant_srd          35265 non-null  object
 66  lab_wge                35265 non-null  object
 67  lab_bus                35265 non-null  object
 68  lab_vol                35265 non-null  object
 69  lab_ret                35265 non-null  object
 70  lab_amount             35265 non-null  object
 71  lab_sto                35265 non-null  object
 72  lab_salper             35265 non-null  object
 73  lab_salc               35265 non-null  object
 74  lab_look               35265 non-null  object
 75  lab_start              35265 non-null  object
 76  lab_rnsw               35265 non-null  object
 77  lab_accjob             35265 non-null  object
 78  undisab                35265 non-null  object
 79  disab                  35265 non-null  object
 80  sevdisab               35265 non-null  object
 81  stratum                35265 non-null  int64
 82  geotype                35265 non-null  int64
 83  lab_salary             35265 non-null  object
 84  employ_Status1         35265 non-null  object
 85  employ_Status2         35265 non-null  object
 86  metro                  35265 non-null  object
 87  metro_code             35265 non-null  object
 88  rotation               35265 non-null  object
 89  person_wgt             35265 non-null  float64
dtypes: float64(1), int64(6), object(83)
memory usage: 24.2+ MB

In [372]:
data_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66144 entries, 0 to 66143
Columns: 112 entries, uqnr to person_wgt
dtypes: float64(1), int64(6), object(105)
memory usage: 56.5+ MB

From the information, we see that the number of columns in our datasets ranges from 90 to 214. The datasets with no detailed information have too many columns to be displayed individually.

In [373]:
datasets = [data_2014, data_2015, data_2016, data_2017, data_2018, data_2021, data_2022]
names = ['2014', '2015', '2016', '2017', '2018', '2021','2022']
def duplicates(data, file_name):
  duplicate_count = data.duplicated().sum()
  print(f"Number of duplicate rows in {file_name}: {duplicate_count}")
  print('===============================================================================')

for dataset, name in zip(datasets, names):
  duplicates(dataset, name)

Number of duplicate rows in 2014: 0
===============================================================================
Number of duplicate rows in 2015: 0
===============================================================================
Number of duplicate rows in 2016: 0
===============================================================================
Number of duplicate rows in 2017: 0
===============================================================================
Number of duplicate rows in 2018: 0
===============================================================================
Number of duplicate rows in 2021: 0
===============================================================================
Number of duplicate rows in 2022: 0
===============================================================================

From the output we got above, there are no duplicates in the datasets we are working with. Now we are going to check if there are any null values in the datasets.

In [374]:
def nulls(data, file_name):
  null_count = data.isnull().sum()
  print(f"Number of null rows in {file_name}: {null_count}")
  print('===============================================================================')

for dataset, name in zip(datasets, names):
  nulls(dataset, name)

Number of null rows in 2014: uqnr              0
personnr          0
psu               0
prov              0
B_NIGHTS          0
                 ..
employ_Status1    0
employ_Status2    0
stratum           0
rotation          0
person_wgt        0
Length: 183, dtype: int64
===============================================================================
Number of null rows in 2015: uqnr              0
personnr          0
psu               0
prov              0
B_NIGHTS          0
                 ..
Metro             0
employ_Status1    0
employ_Status2    0
rotation          0
person_wgt        0
Length: 183, dtype: int64
===============================================================================
Number of null rows in 2016: UqNr              0
PersonNR          0
PSU               0
Prov              0
B_Nights          0
                 ..
Metro             0
employ_Status1    0
employ_Status2    0
Rotation          0
person_wgt        0
Length: 214, dtype: int64
===============================================================================
Number of null rows in 2017: UqNr              0
PersonNR          0
PSU               0
Prov              0
B_Nights          0
                 ..
Metro             0
employ_Status1    0
employ_Status2    0
Rotation          0
person_wgt        0
Length: 183, dtype: int64
===============================================================================
Number of null rows in 2018: UqNr              0
PersonNR          0
PSU               0
Prov              0
B_Nights          0
                 ..
Metro             0
employ_Status1    0
employ_Status2    0
Rotation          0
person_wgt        0
Length: 185, dtype: int64
===============================================================================
Number of null rows in 2021: uqnr              0
personnr          0
psu               0
prov              0
Four_by_Four      0
                 ..
employ_Status2    0
metro             0
metro_code        0
rotation          0
person_wgt        0
Length: 90, dtype: int64
===============================================================================
Number of null rows in 2022: uqnr              0
personnr          0
psu               0
prov              0
Four_by_Four      0
                 ..
lab_salary        0
employ_Status1    0
employ_Status2    0
rotation          0
person_wgt        0
Length: 112, dtype: int64
===============================================================================

From the output, we can see that there are no null values. This means that we will not have to remove duplicates and nulls during our data cleaning process. We will be moving to feature selection.

The following are the features we chose and the reasons why we chose them:

Demographics: Age, Gender, Race
Household/Family: Relationship, Marital_Status
Education: Education, Literacy3b, edu_attend
Health: hlt_genhealth, disab, sevidisab
Geographical: prov, Metro, geotype, stratum
Income/Employement: lab_salary, employ_Status1, employ_Status2

We chose these features as they affect employment status and they provide meaningful information. The other features either do not have enough information, or they do not directly affect employment status.

In [375]:
data2014 = data_2014.copy()
data2015 = data_2015.copy()
data2016 = data_2016.copy()
data2017 = data_2017.copy()
data2018 = data_2018.copy()
data2021 = data_2021.copy()
data2022 = data_2022.copy()

We copied the datasets so that the changes we make do not affect the original datasets, and for easy control of mistakes.

#DATA CLEANING

In [376]:
data2014.head()

,uqnr,personnr,psu,prov,B_NIGHTS,gender,Age,age_grp,race,q11RELSH,q12aMARST,Q12bSPOU,Q12CPSNN,Q13aFATH,Q13bFalive,Q13cFPAR,Q13dFPSN,Q14aMOTH,Q14bMalive,Q14cMPAR,Q14dMPSN,Q15HIEDU,Q16ATECHILD,Q17DA,Q18ECD,Q19WRTN,Q19READ,Q19FORM,Q19WRTL,Q19CAL,Q19RDSN,Q110ATTE,Q111RSNN,Q112EDUI,Q113PPRIV,Q114DLRN,Q115aMOD,Q115bTIM,Q115cNR,Q115dNNI,Q116FEET,Q117RNFE,Q118BURS,Q119ALanguage,Q119Amathematics,Q119BTEXTBOOKS,Q119cBOOK,Q119cPOOR,Q119cLACK,Q119cBADC,Q119cFEES,Q119cCLAS,Q119cTABS,Q119cPMAN,Q119cOTHR,Q120GRDE,Q121SAME,Q122aFOOD,Q122bEFOOD,Q123aVIOL,Q123bVIOL1,Q123bVIOL2,Q123bVIOL3,Q123bVIOL4,Q123bVIOL5,Q123bVIOL6,Q124aABS,Q124bDAY,Q124cRSN,Q21MEDI,Q22GENHEALTH,Q23FLU,Q23DIA,Q23SCblood,Q23SUB,Q23DEP,Q23SEX,Q23PNEU,Q23BRON,Q23EPIL,Q24aCON,Q24bYNT,Q25aMVHoccupant,Q25aMVHpedestrian,Q25aBCL,Q25aGUN,Q25aSTR,Q25aCrime,Q25aFIRE,Q25aACCP,Q25aINTP,Q25aSPORTS,Q25aOTH,Q25bmiss,Q26aASM,Q26aDBT,Q26aCAN,Q26aHIV,Q26aHBP,Q26aRTH,Q26aSTRK,Q26aHEART,Q26aTB,Q26aMental,Q26aEPIL,Q26aMEN,Q26aPNEU,Q26aBRON,Q26aCHOLE,Q26aOSTER,Q26aOTH,Q26bASM,Q26bDBT,Q26bCAN,Q26bHIV,Q26bHBP,Q26bRTH,Q26bSTRK,Q26bHEART,Q26bTB,Q26bMental,Q26bEPIL,Q26bMEN,Q26bPNEU,Q26bBRON,Q26bCHOLE,Q26bOSTER,Q26bOTH,Q27aPRE,Q27bSTA,Q28SEE,Q28HEA,Q28WAL,Q28REM,Q28SEL,Q28COM,Q29EYE,Q29HAID,Q29WST,Q29WCH,Q29CMED,Q29OTH,Q31aSG,Q31bOAG,Q31bDIS,Q31bCSG,Q31bCAR,Q31bFOS,Q31bWVT,Q31bGRN,Q31bSOC,Q32DISG,Q41aWGE,Q41bBUS,Q41cVOL,Q41dRET,Q42aSTO,Q42bSP,Q43SALC,Q44aTM,Q44bMIN,Q45SEC,Q46aLOOK,Q46bSTART,Q46cRNSW,Q46dAccJOB,Q47JCR,Q48CELL,Q49RELIGIOUS,Q410ATEREL,Q411RESP,undisab,disab,sevdisab,literacy3b,geotype,q42msal,Metro,employ_Status1,employ_Status2,stratum,rotation,person_wgt
0,101000170000001501,1,10100017000,1,1,1,33,7,4,1,2,1,2,1,8,2,88,1,8,9,99,12,8,8,8,8,8,8,8,8,8,2,6,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,1,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,8,1,1,1,1,1,1,2,2,2,2,1,2,2,8,8,8,8,8,8,8,8,8,1,2,2,9,8000,2,99,2,1,1,9,9,99,9,2,1,1,4,2,0,0,0,0,5,8000,2,1,1,101501,4,512.302826
1,101000170000001501,2,10100017000,1,1,2,29,6,4,2,1,1,1,1,8,2,88,1,8,9,99,23,8,8,8,8,8,8,8,8,8,2,8,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,1,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,1,2,9,5000,2,99,1,8,2,9,9,99,9,2,1,1,4,2,0,0,0,0,5,5000,2,1,1,101501,4,512.302826
2,101000170000001501,3,10100017000,1,1,1,1,1,4,3,7,8,88,1,8,1,1,1,8,1,2,98,6,1,1,8,8,8,8,8,8,8,88,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,1,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,8,8,8,8,8,8,8,8,8,8,8,8,888888888,8,88,88,8,8,8,8,88,8,8,2,99,4,2,0,0,0,0,5,888888888,2,8,8,101501,4,512.302826
3,101000170000005701,1,10100017000,1,1,1,46,10,2,1,2,1,2,2,2,8,88,2,2,8,88,10,8,8,8,8,8,8,8,8,8,2,6,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,5,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,1,2,2,9,450,1,99,2,1,1,9,9,99,9,2,2,1,2,2,0,0,0,0,5,1800,2,1,1,101501,4,304.050736
4,101000170000005701,2,10100017000,1,1,2,49,10,2,2,2,1,1,2,2,8,88,2,2,8,88,1,8,8,8,1,1,2,2,1,1,2,10,88,8,8,88,8,8,88,88,8,8,8,8,8,8,8,8,8,8,8,8,8,8,88,8,8,8,8,8,8,8,8,8,8,8,8,88,2,3,2,2,2,2,2,2,2,2,2,8,88,2,2,2,2,2,2,2,2,2,2,2,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,2,8,1,1,1,1,1,1,2,2,2,2,2,2,2,8,8,8,8,8,8,8,8,8,2,2,2,2,888888888,8,88,88,8,8,2,2,88,8,2,2,1,2,2,0,0,0,0,5,888888888,2,9,3,101501,4,304.050736

In [377]:
# List of columns to keep based on their relevance for the model
columns_to_keep = [
    # Demographic
    'gender',         # V321
    'Age',            # V322
    'race',           # V324
    'Q15HIEDU',       # Highest education level (V339)

    # Household
    'q11RELSH',       # Relationship to the household head (V327)
    'q12aMARST',      # Marital status (V328)

    # Education
    'Q110ATTE',       # Currently attending educational institution (V358)

    # Health
    'Q21MEDI',        # Medical aid scheme (V396)
    'Q22GENHEALTH',   # Health status (V397)

    # Geographic
    'psu',            # Primary sampling unit (V318)
    'prov',           # Province (V319)
    'geotype',        # Geography Type (V493)
    'Metro',          # Metro (V496)

    # Income/Employment
    'employ_Status1', # Employment Status 1 (V497)
    'employ_Status2', # Employment Status 2 (V498)
    'q42msal'         # Monthly Salary (V494)
]

# Select the columns
data2014_selected = data2014[columns_to_keep]

# Display the selected columns
print("Selected Columns for Employment Prediction Model:")
print(data2014_selected.head())

# Optionally, save the selected columns to a new CSV file
data2014_selected.to_csv('employment_prediction_dataset.csv', index=False)

Selected Columns for Employment Prediction Model:
   gender  Age  race  Q15HIEDU  q11RELSH  q12aMARST  Q110ATTE  Q21MEDI  \
0       1   33     4        12         1          2         2        1
1       2   29     4        23         2          1         2        1
2       1    1     4        98         3          7         8        1
3       1   46     2        10         1          2         2        2
4       2   49     2         1         2          2         2        2

   Q22GENHEALTH          psu  prov  geotype  Metro  employ_Status1  \
0             3  10100017000     1        5      2               1
1             3  10100017000     1        5      2               1
2             3  10100017000     1        5      2               8
3             5  10100017000     1        5      2               1
4             3  10100017000     1        5      2               9

   employ_Status2    q42msal
0               1       8000
1               1       5000
2               8  888888888
3               1       1800
4               3  888888888

In [378]:
# List of columns to keep based on their relevance for the model
columns_to_keep = [
    # Demographic
    'gender',         # V321
    'Age',            # V322
    'race',           # V324
    'Q15HIEDU',       # Highest education level (V339)

    # Household
    'q11RELSH',       # Relationship to the household head (V327)
    'q12aMARST',      # Marital status (V328)

    # Education
    'Q110ATTE',       # Currently attending educational institution (V358)

    # Health
    'Q21MEDI',        # Medical aid scheme (V396)
    'Q22GENHEALTH',   # Health status (V397)

    # Geographic
    'psu',            # Primary sampling unit (V318)
    'prov',           # Province (V319)
    'GeoType',        # Geography Type (V493)
    'Metro',          # Metro (V496)

    # Income/Employment
    'employ_Status1', # Employment Status 1 (V497)
    'employ_Status2', # Employment Status 2 (V498)
    'q42msal'         # Monthly Salary (V494)
]

# Select the columns
data2015_selected = data2015[columns_to_keep]

# Display the selected columns
print("Selected Columns for Employment Prediction Model:")
print(data2015_selected.head())

# Optionally, save the selected columns to a new CSV file
data2015_selected.to_csv('employment_prediction_dataset.csv', index=False)

Selected Columns for Employment Prediction Model:
   gender  Age  race  Q15HIEDU  q11RELSH  q12aMARST  Q110ATTE  Q21MEDI  \
0       1   48     2         3         1          6         2        2
1       1   43     2         8         1          2         2        2
2       2   42     2         7         2          2         2        2
3       1   54     2         9         1          2         2        2
4       2   36     2         8         2          2         2        2

   Q22GENHEALTH          psu  prov  GeoType  Metro  employ_Status1  \
0             3  16010072000     1        3      2               1
1             3  16010072000     1        3      2               1
2             3  16010072000     1        3      2               9
3             5  16010072000     1        3      2               9
4             3  16010072000     1        3      2               1

   employ_Status2    q42msal
0               1       2640
1               1       2400
2               3  888888888
3               3  888888888
4               1       2000

In [379]:
# List of columns to keep based on their relevance for the model
columns_to_keep = [
    # Demographic
    'Gender',         # V321
    'Age',            # V322
    'Race',           # V324
    'Q15HIEDU',       # Highest education level (V339)

    # Household
    'Q11RELSH',       # Relationship to the household head (V327)
    'Q12aMARST',      # Marital status (V328)

    # Education
    'Q110ATTE',       # Currently attending educational institution (V358)

    # Health
    'Q21MEDI',        # Medical aid scheme (V396)
    'Q22GENHEALTH',   # Health status (V397)

    # Geographic
    'PSU',            # Primary sampling unit (V318)
    'Prov',           # Province (V319)
    'geotype',        # Geography Type (V493)
    'Metro',          # Metro (V496)

    # Income/Employment
    'employ_Status1', # Employment Status 1 (V497)
    'employ_Status2', # Employment Status 2 (V498)
    'Q42msal'         # Monthly Salary (V494)
]

# Select the columns
data2016_selected = data2016[columns_to_keep]

# Display the selected columns
print("Selected Columns for Employment Prediction Model:")
print(data2016_selected.head())

# Optionally, save the selected columns to a new CSV file
data2016_selected.to_csv('employment_prediction_dataset.csv', index=False)

Selected Columns for Employment Prediction Model:
   Gender  Age  Race  Q15HIEDU  Q11RELSH  Q12aMARST  Q110ATTE  Q21MEDI  \
0       1   49     2         2         1          2         2        2
1       2   54     2         7         2          2         2        2
2       2   25     2         9         3          7         2        2
3       1    1     2        98         9          7         8        2
4       1   29     1        12         1          1         2        2

   Q22GENHEALTH          PSU  Prov  geotype  Metro  employ_Status1  \
0             3  16010072000     1        3      2               1
1             3  16010072000     1        3      2               1
2             3  16010072000     1        3      2               1
3             3  16010072000     1        3      2               8
4             3  16010072000     1        3      2               1

   employ_Status2    Q42msal
0               1       3004
1               1       2760
2               1       2000
3               8  888888888
4               1       6000

In [380]:
# List of columns to keep based on their relevance for the model
columns_to_keep = [
    # Demographic
    'Gender',         # V321
    'Age',            # V322
    'Race',           # V324
    'Q15HIEDU',       # Highest education level (V339)

    # Household
    'Q11RELSH',       # Relationship to the household head (V327)
    'Q12aMARST',      # Marital status (V328)

    # Education
    'Q110ATTE',       # Currently attending educational institution (V358)

    # Health
    'Q21MEDI',        # Medical aid scheme (V396)
    'Q22GENHEALTH',   # Health status (V397)

    # Geographic
    'PSU',            # Primary sampling unit (V318)
    'Prov',           # Province (V319)
    'geotype',        # Geography Type (V493)
    'Metro',          # Metro (V496)

    # Income/Employment
    'employ_Status1', # Employment Status 1 (V497)
    'employ_Status2', # Employment Status 2 (V498)
    'Q42msal'         # Monthly Salary (V494)
]

# Select the columns
data2017_selected = data2017[columns_to_keep]

# Display the selected columns
print("Selected Columns for Employment Prediction Model:")
print(data2017_selected.head())

# Optionally, save the selected columns to a new CSV file
data2017_selected.to_csv('employment_prediction_dataset.csv', index=False)

Selected Columns for Employment Prediction Model:
   Gender  Age  Race  Q15HIEDU  Q11RELSH  Q12aMARST  Q110ATTE  Q21MEDI  \
0       1   50     2         2         1          5         2        2
1       1   29     1        11         1          2         2        2
2       2   24     1        11         2          2         2        2
3       2    0     1        98         3          7         8        2
4       2   70     2         6         1          7         2        2

   Q22GENHEALTH          PSU  Prov  geotype  Metro  employ_Status1  \
0             3  16010072000     1        3      2               1
1             1  16010072000     1        3      2               1
2             1  16010072000     1        3      2               9
3             1  16010072000     1        3      2               8
4             2  16010122000     1        1      2               9

   employ_Status2    Q42msal
0               1       3400
1               1       2000
2               3  888888888
3               8  888888888
4               3  888888888

In [381]:
# List of columns to keep based on their relevance for the model
columns_to_keep = [
    # Demographic
    'Gender',         # V321
    'Age',            # V322
    'Race',           # V324
    'Q15HIEDU',       # Highest education level (V339)

    # Household
    'Q11RELSH',       # Relationship to the household head (V327)
    'Q12aMARST',      # Marital status (V328)

    # Education
    'Q110ATTE',       # Currently attending educational institution (V358)

    # Health
    'Q21MEDI',        # Medical aid scheme (V396)
    'Q22GENHEALTH',   # Health status (V397)

    # Geographic
    'PSU',            # Primary sampling unit (V318)
    'Prov',           # Province (V319)
    'geotype',        # Geography Type (V493)
    'Metro',          # Metro (V496)

    # Income/Employment
    'employ_Status1', # Employment Status 1 (V497)
    'employ_Status2', # Employment Status 2 (V498)
    'Q42msal'         # Monthly Salary (V494)
]

# Select the columns
data2018_selected = data2018[columns_to_keep]

# Display the selected columns
print("Selected Columns for Employment Prediction Model:")
print(data2018_selected.head())

# Optionally, save the selected columns to a new CSV file
data2018_selected.to_csv('employment_prediction_dataset.csv', index=False)

Selected Columns for Employment Prediction Model:
   Gender  Age  Race  Q15HIEDU  Q11RELSH  Q12aMARST  Q110ATTE  Q21MEDI  \
0       1   19     2         8         1          7         2        2
1       1   31     1        11         1          2         2        2
2       2   25     1        11         2          2         2        2
3       2    1     1        98         3          7         8        2
4       2   71     2         7         1          7         2        2

   Q22GENHEALTH          PSU  Prov  geotype  Metro  employ_Status1  \
0             2  16010072000     1        3      2               1
1             2  16010072000     1        3      2               1
2             2  16010072000     1        3      2               1
3             2  16010072000     1        3      2               8
4             4  16010122000     1        1      2               9

   employ_Status2    Q42msal
0               1       2900
1               1      12480
2               1       8960
3               8  888888888
4               3  888888888

In [382]:
data2021.head()

,uqnr,personnr,psu,prov,Four_by_Four,Sex,age,age_grp1,Population,hhc_relationship,hhc_marital,spouse,spouse_name,hhc_fath_alive,hhc_fath_parthh,hhc_fath_name,hhc_moth_alive,hhc_moth_parthh,hhc_moth_name,education,ecd_chldatt,ecd_notatt,ecd_notatt_rsn,ecd_fees,edu_attend,edu_rsnn,edu_edui,edu_ppriv,edu_corr,edu_homesch,edu_attfreq,edu_homesch_part,edu_homesch_smrtphone,edu_homesch_computer,edu_homesch_tablet,edu_homesch_printed,edu_burs,edu_totfees,edu_nofees,edu_grde,edu_same,edu_food,edu_eatfood,hlt_medi,hlt_covid_postest,hlt_chronic_asm,hlt_chronic_dbt,hlt_chronic_hbp,hlt_chronic_strk,hlt_preg,hlt_chronic_tb,dsb_see,dsb_hea,dsb_wal,dsb_rem,dsb_sel,dsb_com,soc_grant,soc_grant_oag,soc_grant_dis,soc_grant_csg,soc_grant_car,soc_grant_fos,soc_grant_wvt,soc_grant_grn,soc_grant_srd,lab_wge,lab_bus,lab_vol,lab_ret,lab_amount,lab_sto,lab_salper,lab_salc,lab_look,lab_start,lab_rnsw,lab_accjob,undisab,disab,sevdisab,stratum,geotype,lab_salary,employ_Status1,employ_Status2,metro,metro_code,rotation,person_wgt
0,160100090000003901,1,16010009000,Western Cape,Yes,Male,78,75+,White,Head/acting head,Legally married,Yes,2,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Yes,No,Not applicable,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,Yes,No,Not applicable,No,DO NOT KNOW:,Not applicable,15,Not applicable,Not applicable,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10301,3,Unspecified,Employed,Employed,Non-metro,WC - Non-metro,Quarter 3,2970.762309
1,160100090000003901,2,16010009000,Western Cape,Yes,Female,75,75+,White,Husband/wife/partner of household head,Legally married,Yes,1,No,Not applicable,Not applicable,No,Not applicable,Not applicable,Grade 10/Standard 8/Form 3/NCV Level 2/Occupat...,Not applicable,Not applicable,Not applicable,Not applicable,No,Too old/young,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,Yes,Yes,No,Not applicable,No,A lot of difficulty,No difficulty,A lot of difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,DO NOT KNOW:,Not applicable,Not applicable,No,No,Not applicable,Not applicable,Disabled,Disabled,Disabled,10301,3,Not applicable,Unspecified,Not economically active,Non-metro,WC - Non-metro,Quarter 3,2971.535495
2,160100630000010801,1,16010063000,Western Cape,Yes,Female,28,25-29,Coloured,Head/acting head,Living together like husband and wife/partners,Yes,2,Yes,No,Not applicable,No,Not applicable,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,No,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,Not applicable,No,DO NOT KNOW:,Not applicable,7,Not applicable,Not applicable,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10106,1,4017,Employed,Employed,Non-metro,WC - Non-metro,Quarter 3,5611.998377
3,160100630000010801,2,16010063000,Western Cape,Yes,Male,40,40-44,Coloured,Husband/wife/partner of household head,Living together like husband and wife/partners,Yes,1,No,Not applicable,Not applicable,Yes,No,Not applicable,Grade 12/Standard 10/Form 5/National Senior Ce...,Not applicable,Not applicable,Not applicable,Not applicable,No,He or she is working at home or business/job,Not Applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,No,No,Not applicable,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Yes,No,No,Not applicable,No,DO NOT KNOW:,Not applicable,14,Not applicable,Not applicable,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10106,1,2029,Employed,Employed,Non-metro,WC - Non-metro,Quarter 3,5585.705994
4,160100630000010801,3,16010063000,Western Cape,Yes,Female,17,15-19,Coloured,Son/daughter/stepchild/adopted child of househ...,Single and have never been married/never lived...,Not applicable,Not applicable,Yes,No,Not applicable,Yes,Yes,Unspecified,Grade 8/Standard 6/Form 1,Not applicable,Not applicable,Not applicable,Not applicable,Yes,Not applicable,School (including Grade R to Grade 12 learners...,Public (Government),No,No,Four days,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,NaN,No fee school (School does not ask for tuition...,Grade 9,No,Yes,"Yes, a few times a week",No,No,No,No,No,No,No,No,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No difficulty,No,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,Not applicable,No,No,No,No,Do not know,DO NOT KNOW:,Not applicable,Not applicable,No,No,Not applicable,Not applicable,Not disabled,Not disabled,Not disabled,10106,1,Not applicable,Unspecified,Not economically active,Non-metro,WC - Non-metro,Quarter 3,5595.212493

In [383]:
try:
    # Load your dataset
    #data_2021 = pd.read_csv('/content/drive/MyDrive/Data Science 2024/qualifying dataset/Team Qualifier Dataset and Document/ghs-2021-person-v1.csv',encoding = 'latin-1')

    # List of columns to keep based on their relevance for the model
    columns_to_keep = [
        # Demographic
        'Sex',             # Sex (Assumed to match 'Gender')
        'age',             # Age (Assumed to match 'Age')

        # Household
        'hhc_marital',     # Marital status (Assumed to match 'Q12aMARST')
        'education',       # Highest education level (Assumed to match 'Q15HIEDU')
        'Population',      # Total population in household (Assumed to be an appropriate column)

        # Household Relationship
        'hhc_relationship', # Relationship to the household head (Assumed to match 'Q11RELSH')

        # Education
        'edu_attend',      # Currently attending educational institution (Assumed to match 'Q110ATTE')

        # Health
        'hlt_medi',        # Medical aid scheme (Assumed to match 'Q21MEDI')
        'disab',           # Disability (Assumed to be an appropriate column; may need to be mapped from multiple columns)
        'sevdisab',       # Severity of disability (Assumed to be an appropriate column)

        # Geographic
        'prov',            # Province (Assumed to match 'Prov')
        'metro',           # Metro (Assumed to match 'Metro')
        'geotype',         # Geography Type (Assumed to match 'geotype')
        'stratum',         # Primary sampling unit or stratum (Assumed to be mapped from 'PSU')

        # Income/Employment
        'lab_salary',      # Monthly Salary (Assumed to match 'Q42msal')
        'employ_Status1',  # Employment Status 1 (Assumed to match 'employ_Status1')
        'employ_Status2'   # Employment Status 2 (Assumed to match 'employ_Status2')
    ]

    # Check if all columns in columns_to_keep are in the DataFrame
    missing_cols = [col for col in columns_to_keep if col not in data_2022.columns]
    if missing_cols:
        raise ValueError(f"Missing columns: {missing_cols}")

    # Filter the DataFrame to keep only the specified columns
    data2021_selected = data2021[columns_to_keep]

    # Display the first few rows of the filtered DataFrame to verify
    print(data2021_selected.head())

except FileNotFoundError as e:
    print(f"Error: {e}")
except ValueError as e:
    print(f"Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

      Sex  age                                        hhc_marital  \
0    Male   78                                    Legally married
1  Female   75                                    Legally married
2  Female   28     Living together like husband and wife/partners
3    Male   40     Living together like husband and wife/partners
4  Female   17  Single and have never been married/never lived...

                                           education Population  \
0  Grade 12/Standard 10/Form 5/National Senior Ce...      White
1  Grade 10/Standard 8/Form 3/NCV Level 2/Occupat...      White
2  Grade 12/Standard 10/Form 5/National Senior Ce...   Coloured
3  Grade 12/Standard 10/Form 5/National Senior Ce...   Coloured
4                          Grade 8/Standard 6/Form 1   Coloured

                                    hhc_relationship edu_attend hlt_medi  \
0                                   Head/acting head         No       No
1             Husband/wife/partner of household head         No       No
2                                   Head/acting head         No       No
3             Husband/wife/partner of household head         No       No
4  Son/daughter/stepchild/adopted child of househ...        Yes       No

          disab      sevdisab          prov      metro  geotype  stratum  \
0  Not disabled  Not disabled  Western Cape  Non-metro        3    10301
1      Disabled      Disabled  Western Cape  Non-metro        3    10301
2  Not disabled  Not disabled  Western Cape  Non-metro        1    10106
3  Not disabled  Not disabled  Western Cape  Non-metro        1    10106
4  Not disabled  Not disabled  Western Cape  Non-metro        1    10106

       lab_salary employ_Status1           employ_Status2
0     Unspecified       Employed                 Employed
1  Not applicable    Unspecified  Not economically active
2            4017       Employed                 Employed
3            2029       Employed                 Employed
4  Not applicable    Unspecified  Not economically active

In [384]:
try:
    # Load your dataset
    #data_2022 = pd.read_csv('/content/drive/MyDrive/Data Science 2024/qualifying dataset/Team Qualifier Dataset and Document/ghs-2022-person-v1.csv',encoding = 'latin-1')

    # List of columns to keep based on their relevance for the model
    columns_to_keep = [
        # Demographic
        'Sex',             # Sex (Assumed to match 'Gender')
        'age',             # Age (Assumed to match 'Age')

        # Household
        'hhc_marital',     # Marital status (Assumed to match 'Q12aMARST')
        'education',       # Highest education level (Assumed to match 'Q15HIEDU')
        'Population',      # Total population in household (Assumed to be an appropriate column)

        # Household Relationship
        'hhc_relationship', # Relationship to the household head (Assumed to match 'Q11RELSH')

        # Education
        'edu_attend',      # Currently attending educational institution (Assumed to match 'Q110ATTE')

        # Health
        'hlt_medi',        # Medical aid scheme (Assumed to match 'Q21MEDI')
        'disab',           # Disability (Assumed to be an appropriate column; may need to be mapped from multiple columns)
        'sevdisab',       # Severity of disability (Assumed to be an appropriate column)

        # Geographic
        'prov',            # Province (Assumed to match 'Prov')
        'metro',           # Metro (Assumed to match 'Metro')
        'geotype',         # Geography Type (Assumed to match 'geotype')
        'stratum',         # Primary sampling unit or stratum (Assumed to be mapped from 'PSU')

        # Income/Employment
        'lab_salary',      # Monthly Salary (Assumed to match 'Q42msal')
        'employ_Status1',  # Employment Status 1 (Assumed to match 'employ_Status1')
        'employ_Status2'   # Employment Status 2 (Assumed to match 'employ_Status2')
    ]

    # Check if all columns in columns_to_keep are in the DataFrame
    missing_cols = [col for col in columns_to_keep if col not in data_2022.columns]
    if missing_cols:
        raise ValueError(f"Missing columns: {missing_cols}")

    # Filter the DataFrame to keep only the specified columns
    data2022_selected = data2022[columns_to_keep]

    # Display the first few rows of the filtered DataFrame to verify
    print(data2022_selected.head())

except FileNotFoundError as e:
    print(f"Error: {e}")
except ValueError as e:
    print(f"Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

      Sex  age                                        hhc_marital  \
0    Male   79                                    Legally married
1  Female   76                                    Legally married
2    Male   31     Living together like husband and wife/partners
3  Female   34     Living together like husband and wife/partners
4    Male   12  Single and have never been married/never lived...

                                           education Population  \
0  GRADE 12/STANDARD 10/FORM 5/NATIONAL SENIOR CE...      White
1  GRADE 10/STANDARD 8/FORM 3/NCV LEVEL 2/OCCUPAT...      White
2  GRADE 10/STANDARD 8/FORM 3/NCV LEVEL 2/OCCUPAT...   Coloured
3  GRADE 12/STANDARD 10/FORM 5/NATIONAL SENIOR CE...   Coloured
4                      GRADE 5/STANDARD 3/ABET/AET 2   Coloured

                                    hhc_relationship edu_attend hlt_medi  \
0                                   Head/acting head         No      Yes
1             Husband/wife/partner of household head         No      Yes
2                                   Head/acting head         No       No
3             Husband/wife/partner of household head         No       No
4  Son/daughter/stepchild/adopted child of househ...        Yes       No

          disab      sevdisab          prov      metro  geotype  stratum  \
0      Disabled  Not disabled  Western Cape  Non-metro        3    10301
1      Disabled  Not disabled  Western Cape  Non-metro        3    10301
2  Not disabled  Not disabled  Western Cape  Non-metro        3    10301
3  Not disabled  Not disabled  Western Cape  Non-metro        3    10301
4  Not disabled  Not disabled  Western Cape  Non-metro        3    10301

       lab_salary  employ_Status1           employ_Status2
0     Unspecified        Employed                 Employed
1  Not applicable     Unspecified  Not economically active
2            3929        Employed                 Employed
3  Not applicable     Unspecified  Not economically active
4  Not applicable  Not applicable           Not applicable

encoding!!!???

In [386]:
#mapping categorical values to numeric
data2022_selected['Sex'].replace(['Male','Female'], [1,2], inplace=True)
data2021_selected['Sex'].replace(['Male','Female'], [1,2], inplace=True)

data2022_selected['hhc_marital'].replace(['Legally married', 'Living together like husband and wife/partners', 'Divorced',
                                             'Separated, but still legally married', 'Widowed', 'Single, but have lived together with someone as husband/wife before', 'Single and have never been married/never lived together as husband/wife before', 'Unspecified'],[1,2,3,4,5,6,7,9], inplace = True)
data2021_selected['hhc_marital'].replace(['Legally married', 'Living together like husband and wife/partners', 'Divorced',
                                             'Separated, but still legally married', 'Widowed', 'Single, but have lived together with someone as husband/wife before', 'Single and have never been married/never lived together as husband/wife before', 'Unspecified'],[1,2,3,4,5,6,7,9], inplace = True)


data2022_selected['Population'].replace(['African/Black', 'Coloured', 'Indian/Asian', 'White'], [1,2,3,4], inplace=True)
data2021_selected['Population'].replace(['African/Black', 'Coloured', 'Indian/Asian', 'White'], [1,2,3,4], inplace=True)

data2022_selected['prov'].replace(['Western Cape','Eastern Cape', 'Northern Cape', 'Free State', 'KwaZulu Natal',
                                    'North West', 'Gauteng', 'Mpumalanga', 'Limpopo'], [1,2,3,4,5,6,7,8,9], inplace=True)
data2021_selected['prov'].replace(['Western Cape','Eastern Cape', 'Northern Cape', 'Free State', 'KwaZulu Natal',
                                    'North West', 'Gauteng', 'Mpumalanga', 'Limpopo'], [1,2,3,4,5,6,7,8,9], inplace=True)

data2021_selected['education'].replace(['Grade R/0','Grade 1/Sub A/Class 1','Grade 2/Sub B/Class 2','Grade 3/Standard 1/ABET/AET 1',
                                         'Grade 4/Standard 2','Grade 5/Standard 3/ABET/AET 2','Grade 6/Standard 4','Grade 7/Standard 5/ABET/AET 3',
                                         'Grade 8/Standard 6/Form 1','Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate \x96 NQF Level 1',
                                         'Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate \x96 NQF Level 2','Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate \x96 NQF Level 3',
                                         'Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate \x96 NQF Level 4','NTC l/N1/NQF 1',
                                         'NTC ll/N2/NQF 2','NTC lll/N3/NQF 3','N4/NTC 4/Occupational Certificate \x96 NQF Level 5','N5/NTC 5/Occupational Certificate \x96 NQF Level 5',
                                         'N6/NTC 6/Occupational Certificate \x96 NQF Level 5','Certificate with less than Grade 12/Standard 10','Diploma with less than Grade 12/Standard 10',
                                          'Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate \x96 NQF Level 5','Diploma with Grade 12/Standard 10/Occupational Certificate  NQF Level 6',
                                          'Higher Diploma/Occupational Certificate (B-Tech Diploma)  NQF Level 7',
                                         'Bachelor\x92s Degree/Occupational Certificate \x96 NQF Level 7','Honours Degree/Postgraduate Diploma/Occupational Certificate \x96 NQF Level 8',"Post Higher Diploma (M-Tech and Master's Degree) \x96 NQF Level 9"
                                         ,'Doctoral Degrees (D-Tech and PhD) \x96 NQF Level 10',
                                         'Other','DO NOT KNOW','No schooling','Unspecified'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,98,99],
                                        inplace=True)
data2022_selected['education'].replace(['GRADE R/0','GRADE 1/SUB A/CLASS 1','GRADE 2/SUB B/CLASS 2',
                                         'GRADE 3/STANDARD 1/ABET/AET 1','GRADE 4/STANDARD 2','GRADE 5/STANDARD 3/ABET/AET 2',
                                         'GRADE 6/STANDARD 4','GRADE 7/STANDARD 5/ABET/AET 3','GRADE 8/STANDARD 6/FORM 1',
                                         'GRADE 9/STANDARD 7/FORM 2/ABET/AET 4/NCV LEVEL 1/OCCUPATIONAL CERTIFICATE - NQF LEVEL 1',
                                         'GRADE 10/STANDARD 8/FORM 3/NCV LEVEL 2/OCCUPATIONAL CERTIFICATE  NQF LEV EL 2',
                                         'GRADE 11/STANDARD 9/FORM 4/NCV LEVEL 3/OCCUPATIONAL CERTIFICATE  NQF LEV EL 3',
                                         'GRADE 12/STANDARD 10/FORM 5/NATIONAL SENIOR CERTIFICATE/MATRIC/ NCV LEVEL 4 /OCCUPATIONAL CERTIFICATE  NQF LEVEL 4',
                                         'NTC L/N1/NQF 1','NTC LL/N2/NQF 2','NTC LLL/N3/NQF 3','N4/NTC 4/OCCUPATIONAL CERTIFICATE  NQF LEVEL 5',
                                         'N5/NTC 5/OCCUPATIONAL CERTIFICATE  NQF LEVEL 5','N6/NTC 6/OCCUPATIONAL CERTIFICATE  NQF LEVEL 5',
                                         'CERTIFICATE WITH LESS THAN GRADE 12/STANDARD 10','DIPLOMA WITH LESS THAN GRADE 12/STANDARD 10',
                                         'HIGHER/NATIONAL/ADVANCE CERTIFICATE WITH GRADE 12/STD 10/OCCUPATIONAL CERTIFICATE  NQF LEVEL 5',
                                         'DIPLOMA WITH GRADE 12/STANDARD 10/OCCUPATIONAL CERTIFICATE  NQF LEVEL 6',
                                         'HIGHER DIPLOMA/OCCUPATIONAL CERTIFICATE (B-TECH DIPLOMA)  NQF LEVEL 7',
                                         'BACHELORS DEGREE/OCCUPATIONAL CERTIFICATE  NQF LEVEL 7',
                                         'HONOURS DEGREE/POSTGRADUATE DIPLOMA/OCCUPATIONAL CERTIFICATE  NQF LEVEL 8',
                                         "POST HIGHER DIPLOMA (M-TECH AND MASTER'S DEGREE)  NQF LEVEL 9",
                                         'DOCTORAL DEGREES (D-TECH AND PHD)  NQF LEVEL 10',
                                         'OTHER THAN ANY OF THE ABOVE','DO NOT KNOW','NO SCHOOLING','UNSPECIFIED'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,98,99],
                              inplace=True )
data2022_selected['disab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)
data2021_selected['disab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)

data2022_selected['sevdisab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)
data2021_selected['sevdisab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)

data2022_selected['employ_Status1'].replace(['Employed', 'Unemployed', 'Unspecified', 'Not applicable'],[1,2,3,8],inplace=True)
data2021_selected['employ_Status1'].replace(['Employed', 'Unemployed', 'Unspecified', 'Not applicable'],[1,2,3,8],inplace=True)


data2022_selected['employ_Status2'].replace(['Employed', 'Unemployed', 'Not economically active', 'Not applicable'],[1,2,3,8],inplace=True)
data2021_selected['employ_Status2'].replace(['Employed', 'Unemployed', 'Not economically active', 'Not applicable'],[1,2,3,8],inplace=True)

data2021_selected['hhc_relationship'].replace(['Head/acting head', 'Husband/wife/partner of household head', 'Son/daughter/stepchild/adopted child of household head', 'Brother/sister/stepbrother/stepsister of household head', 'Father/mother/stepfather/stepmother of household head', 'Grandparent/great grandparent of household head', 'Grandchild/great grandchild of household head', 'Other relative (e.g. in-laws or aunt/uncle) of household head', 'Non-related persons'], [1,2,3,4,5,6,7,8,9], inplace=True)
data2022_selected['hhc_relationship'].replace(['Head/acting head', 'Husband/wife/partner of household head', 'Son/daughter/stepchild/adopted child of household head', 'Brother/sister/stepbrother/stepsister of household head', 'Father/mother/stepfather/stepmother of household head', 'Grandparent/great grandparent of household head', 'Grandchild/great grandchild of household head', 'Other relative (e.g. in-laws or aunt/uncle) of household head', 'Non-related persons', 'Unspecified'], [1,2,3,4,5,6,7,8,9,99], inplace=True)

data2021_selected['edu_attend'].replace(['Yes', 'No', 'Do not know', 'Not applicable', 'Unspecified'], [1,2,3,8,9], inplace=True)
data2022_selected['edu_attend'].replace(['Yes', 'No', 'Do not know', 'Not applicable'], [1,2,3,8], inplace=True)

data2021_selected['hlt_medi'].replace(['Yes', 'No', 'Do not know', 'Unspecified'], [1,2,3,9], inplace=True)
data2022_selected['hlt_medi'].replace(['Yes', 'No', 'DO NOT KNOW'], [1,2,3], inplace=True)

data2021_selected['metro'].replace(['Metro', 'Non-metro'], [1,2], inplace=True)
data2022_selected['metro'].replace(['Metro', 'Non-metro'], [1,2], inplace=True)

data2021_selected['lab_salary'].replace(['Not applicable', 'Unspecified'], [888888888, 999999999], inplace=True)
data2022_selected['lab_salary'].replace(['Not applicable', 'Unspecified'], [888888888, 999999999], inplace=True)

<ipython-input-386-e9bfcf92371d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['Sex'].replace(['Male','Female'], [1,2], inplace=True)
<ipython-input-386-e9bfcf92371d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['Sex'].replace(['Male','Female'], [1,2], inplace=True)
<ipython-input-386-e9bfcf92371d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['hhc_marital'].replace(['Legally married', 'Living together like husband and wife/partners', 'Divorced',
<ipython-input-386-e9bfcf92371d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['hhc_marital'].replace(['Legally married', 'Living together like husband and wife/partners', 'Divorced',
<ipython-input-386-e9bfcf92371d>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['Population'].replace(['African/Black', 'Coloured', 'Indian/Asian', 'White'], [1,2,3,4], inplace=True)
<ipython-input-386-e9bfcf92371d>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['Population'].replace(['African/Black', 'Coloured', 'Indian/Asian', 'White'], [1,2,3,4], inplace=True)
<ipython-input-386-e9bfcf92371d>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['prov'].replace(['Western Cape','Eastern Cape', 'Northern Cape', 'Free State', 'KwaZulu Natal',
<ipython-input-386-e9bfcf92371d>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['prov'].replace(['Western Cape','Eastern Cape', 'Northern Cape', 'Free State', 'KwaZulu Natal',
<ipython-input-386-e9bfcf92371d>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['education'].replace(['Grade R/0','Grade 1/Sub A/Class 1','Grade 2/Sub B/Class 2','Grade 3/Standard 1/ABET/AET 1',
<ipython-input-386-e9bfcf92371d>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['education'].replace(['GRADE R/0','GRADE 1/SUB A/CLASS 1','GRADE 2/SUB B/CLASS 2',
<ipython-input-386-e9bfcf92371d>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['disab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)
<ipython-input-386-e9bfcf92371d>:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['disab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)
<ipython-input-386-e9bfcf92371d>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['sevdisab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)
<ipython-input-386-e9bfcf92371d>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['sevdisab'].replace(['Not disabled', 'Disabled', 'Unspecified'],[0,1,9], inplace=True)
<ipython-input-386-e9bfcf92371d>:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['employ_Status1'].replace(['Employed', 'Unemployed', 'Unspecified', 'Not applicable'],[1,2,3,8],inplace=True)
<ipython-input-386-e9bfcf92371d>:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['employ_Status1'].replace(['Employed', 'Unemployed', 'Unspecified', 'Not applicable'],[1,2,3,8],inplace=True)
<ipython-input-386-e9bfcf92371d>:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['employ_Status2'].replace(['Employed', 'Unemployed', 'Not economically active', 'Not applicable'],[1,2,3,8],inplace=True)
<ipython-input-386-e9bfcf92371d>:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['employ_Status2'].replace(['Employed', 'Unemployed', 'Not economically active', 'Not applicable'],[1,2,3,8],inplace=True)
<ipython-input-386-e9bfcf92371d>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['hhc_relationship'].replace(['Head/acting head', 'Husband/wife/partner of household head', 'Son/daughter/stepchild/adopted child of household head', 'Brother/sister/stepbrother/stepsister of household head', 'Father/mother/stepfather/stepmother of household head', 'Grandparent/great grandparent of household head', 'Grandchild/great grandchild of household head', 'Other relative (e.g. in-laws or aunt/uncle) of household head', 'Non-related persons'], [1,2,3,4,5,6,7,8,9], inplace=True)
<ipython-input-386-e9bfcf92371d>:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['hhc_relationship'].replace(['Head/acting head', 'Husband/wife/partner of household head', 'Son/daughter/stepchild/adopted child of household head', 'Brother/sister/stepbrother/stepsister of household head', 'Father/mother/stepfather/stepmother of household head', 'Grandparent/great grandparent of household head', 'Grandchild/great grandchild of household head', 'Other relative (e.g. in-laws or aunt/uncle) of household head', 'Non-related persons', 'Unspecified'], [1,2,3,4,5,6,7,8,9,99], inplace=True)
<ipython-input-386-e9bfcf92371d>:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['edu_attend'].replace(['Yes', 'No', 'Do not know', 'Not applicable', 'Unspecified'], [1,2,3,8,9], inplace=True)
<ipython-input-386-e9bfcf92371d>:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['edu_attend'].replace(['Yes', 'No', 'Do not know', 'Not applicable'], [1,2,3,8], inplace=True)
<ipython-input-386-e9bfcf92371d>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['hlt_medi'].replace(['Yes', 'No', 'Do not know', 'Unspecified'], [1,2,3,9], inplace=True)
<ipython-input-386-e9bfcf92371d>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['hlt_medi'].replace(['Yes', 'No', 'DO NOT KNOW'], [1,2,3], inplace=True)
<ipython-input-386-e9bfcf92371d>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['metro'].replace(['Metro', 'Non-metro'], [1,2], inplace=True)
<ipython-input-386-e9bfcf92371d>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['metro'].replace(['Metro', 'Non-metro'], [1,2], inplace=True)
<ipython-input-386-e9bfcf92371d>:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2021_selected['lab_salary'].replace(['Not applicable', 'Unspecified'], [888888888, 999999999], inplace=True)
<ipython-input-386-e9bfcf92371d>:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022_selected['lab_salary'].replace(['Not applicable', 'Unspecified'], [888888888, 999999999], inplace=True)

In [387]:
data2022_selected.tail()

,Sex,age,hhc_marital,education,Population,hhc_relationship,edu_attend,hlt_medi,disab,sevdisab,prov,metro,geotype,stratum,lab_salary,employ_Status1,employ_Status2
66139,2,35,2,10,1,1,2,2,0,0,9,2,2,90401,888888888,3,3
66140,1,11,7,4,1,3,1,2,1,0,9,2,2,90401,888888888,8,8
66141,2,7,7,1,1,3,1,2,0,0,9,2,2,90401,888888888,8,8
66142,2,3,7,98,1,3,8,2,0,0,9,2,2,90401,888888888,8,8
66143,2,1,7,98,1,3,8,2,0,0,9,2,2,90401,888888888,8,8

In [388]:
datasets = [data2014_selected, data2015_selected, data2016_selected, data2017_selected, data2018_selected, data2021_selected, data2022_selected]

#code to map column names to more meaningful names that match across all datasets that we are using
column_name_mapping = {
    'Sex': 'Gender',
    'gender': 'Gender',
    'age': 'Age',
    'race': 'Population',
    'Race': 'Population',
    'hhc_marital': 'Marital_Status',
    'Q12aMARST': 'Marital_Status',
    'q12aMARST': 'Marital_Status',
    'education': 'Highest_Education_Level',
    'Q15HIEDU': 'Highest_Education_Level',
    'hhc_relationship': 'HHC_Relationship', #relationship to the household head
    'Q11RELSH': 'HHC_Relationship',
    'q11RELSH': 'HHC_Relationship',
    'edu_attend': 'Currently_Studying', #Currently attending educational institution
    'Q110ATTE': 'Currently_Studying',
    'hlt_medi': 'Medical_Aid', #Medical aid scheme
    'Q21MEDI': 'Medical_Aid',
    'Q22GENHEALTH': 'Health_Status',
    'disab': 'Disability',
    'sevdisab': 'Severe_Disability',
    'prov': 'Province',
    'Prov': 'Province',
    'metro': 'Metro',
    'geotype': 'GeoType', #Geography type
    'PSU': 'Stratum',
    'psu': 'Stratum',
    'stratum': 'Stratum',
    'lab_salary': 'Monthly_Salary',
    'Q42msal': 'Monthly_Salary',
    'q42msal': 'Monthly_Salary',
    'employ_Status1': 'Employment_Status1',
    'employ_Status2': 'Employment_Status2'
}

for df in datasets:
    # Rename columns using the column_name_mapping dictionary
    df.rename(columns=column_name_mapping, inplace=True)

<ipython-input-388-5f73e5c2e071>:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns=column_name_mapping, inplace=True)

In [389]:
data2014_selected.head()

,Gender,Age,Population,Highest_Education_Level,HHC_Relationship,Marital_Status,Currently_Studying,Medical_Aid,Health_Status,Stratum,Province,GeoType,Metro,Employment_Status1,Employment_Status2,Monthly_Salary
0,1,33,4,12,1,2,2,1,3,10100017000,1,5,2,1,1,8000
1,2,29,4,23,2,1,2,1,3,10100017000,1,5,2,1,1,5000
2,1,1,4,98,3,7,8,1,3,10100017000,1,5,2,8,8,888888888
3,1,46,2,10,1,2,2,2,5,10100017000,1,5,2,1,1,1800
4,2,49,2,1,2,2,2,2,3,10100017000,1,5,2,9,3,888888888

In [390]:
data2015_selected.head()

,Gender,Age,Population,Highest_Education_Level,HHC_Relationship,Marital_Status,Currently_Studying,Medical_Aid,Health_Status,Stratum,Province,GeoType,Metro,Employment_Status1,Employment_Status2,Monthly_Salary
0,1,48,2,3,1,6,2,2,3,16010072000,1,3,2,1,1,2640
1,1,43,2,8,1,2,2,2,3,16010072000,1,3,2,1,1,2400
2,2,42,2,7,2,2,2,2,3,16010072000,1,3,2,9,3,888888888
3,1,54,2,9,1,2,2,2,5,16010072000,1,3,2,9,3,888888888
4,2,36,2,8,2,2,2,2,3,16010072000,1,3,2,1,1,2000

In [395]:
data2016_selected.head()

,Gender,Age,Population,Highest_Education_Level,HHC_Relationship,Marital_Status,Currently_Studying,Medical_Aid,Health_Status,Stratum,Province,GeoType,Metro,Employment_Status1,Employment_Status2,Monthly_Salary
0,1,49,2,2,1,2,2,2,3,16010072000,1,3,2,1,1,3004
1,2,54,2,7,2,2,2,2,3,16010072000,1,3,2,1,1,2760
2,2,25,2,9,3,7,2,2,3,16010072000,1,3,2,1,1,2000
3,1,1,2,98,9,7,8,2,3,16010072000,1,3,2,8,8,888888888
4,1,29,1,12,1,1,2,2,3,16010072000,1,3,2,1,1,6000

In [394]:
data2017_selected.columns.to_list()

['Gender',
 'Age',
 'Population',
 'Highest_Education_Level',
 'HHC_Relationship',
 'Marital_Status',
 'Currently_Studying',
 'Medical_Aid',
 'Health_Status',
 'Stratum',
 'Province',
 'GeoType',
 'Metro',
 'Employment_Status1',
 'Employment_Status2',
 'Monthly_Salary']

In [393]:
data2018_selected.columns.to_list()

['Gender',
 'Age',
 'Population',
 'Highest_Education_Level',
 'HHC_Relationship',
 'Marital_Status',
 'Currently_Studying',
 'Medical_Aid',
 'Health_Status',
 'Stratum',
 'Province',
 'GeoType',
 'Metro',
 'Employment_Status1',
 'Employment_Status2',
 'Monthly_Salary']

In [392]:
data2021_selected.head()

,Gender,Age,Marital_Status,Highest_Education_Level,Population,HHC_Relationship,Currently_Studying,Medical_Aid,Disability,Severe_Disability,Province,Metro,GeoType,Stratum,Monthly_Salary,Employment_Status1,Employment_Status2
0,1,78,1,12,4,1,2,2,0,0,1,2,3,10301,999999999,1,1
1,2,75,1,10,4,2,2,2,1,1,1,2,3,10301,888888888,3,3
2,2,28,2,12,2,1,2,2,0,0,1,2,1,10106,4017,1,1
3,1,40,2,12,2,2,2,2,0,0,1,2,1,10106,2029,1,1
4,2,17,7,8,2,3,1,2,0,0,1,2,1,10106,888888888,3,3

In [391]:
data2022_selected.head()

,Gender,Age,Marital_Status,Highest_Education_Level,Population,HHC_Relationship,Currently_Studying,Medical_Aid,Disability,Severe_Disability,Province,Metro,GeoType,Stratum,Monthly_Salary,Employment_Status1,Employment_Status2
0,1,79,1,12,4,1,2,1,1,0,1,2,3,10301,999999999,1,1
1,2,76,1,10,4,2,2,1,1,0,1,2,3,10301,888888888,3,3
2,1,31,2,10,2,1,2,2,0,0,1,2,3,10301,3929,1,1
3,2,34,2,12,2,2,2,2,0,0,1,2,3,10301,888888888,3,3
4,1,12,7,5,2,3,1,2,0,0,1,2,3,10301,888888888,8,8

In [ ]:
all_datasets = [data_2022, data_2021, data_2018, data_2017, data_2016, data_2015, data_2014]
dataset_names = ['2022', '2021', '2018', '2017', '2016', '2015', '2014']

In [ ]:
def check_column_availability(datasets, target_column):
    availability_dict = {}

    for dataset, dataset_name in zip(datasets, dataset_names):
        availability_dict[dataset_name] = target_column in dataset.columns

    return availability_dict

# Example usage:
column_to_check = 'employ_Status1'  # Replace with the actual column name
availability_result = check_column_availability(all_datasets, column_to_check)

# Display the results
for dataset_name, is_available in availability_result.items():
    print(f"{dataset_name}: {column_to_check} {'is' if is_available else 'is not'} available.")

In [ ]:
def check_column_availability(datasets, target_column):
    availability_dict = {}

    for dataset, dataset_name in zip(datasets, dataset_names):
        availability_dict[dataset_name] = target_column in dataset.columns

    return availability_dict

# Example usage:
column_to_check = 'employ_Status2'  # Replace with the actual column name
availability_result = check_column_availability(all_datasets, column_to_check)

# Display the results
for dataset_name, is_available in availability_result.items():
    print(f"{dataset_name}: {column_to_check} {'is' if is_available else 'is not'} available.")

In [ ]:
# Example usage:
column_to_check = ''  # Replace with the actual column name
availability_result = check_column_availability(all_datasets, column_to_check)

# Display the results
for dataset_name, is_available in availability_result.items():
    print(f"{dataset_name}: {column_to_check} {'is' if is_available else 'is not'} available.")

In [ ]:
data_2019.sample(10)